// Generated by scripts/build.mjs from src/extension/sidepanel-entry.js. Do not edit this file directly.
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// (disabled):crypto
var require_crypto = __commonJS({
  "(disabled):crypto"() {
  }
});

// (disabled):buffer
var require_buffer = __commonJS({
  "(disabled):buffer"() {
  }
});

// node_modules/js-md5/src/md5.js
var require_md5 = __commonJS({
  "node_modules/js-md5/src/md5.js"(exports, module) {
    (function() {
      "use strict";
      var INPUT_ERROR = "input is invalid type";
      var FINALIZE_ERROR = "finalize already called";
      var WINDOW = typeof window === "object";
      var root = WINDOW ? window : {};
      if (root.JS_MD5_NO_WINDOW) {
        WINDOW = false;
      }
      var WEB_WORKER = !WINDOW && typeof self === "object";
      var NODE_JS = !root.JS_MD5_NO_NODE_JS && typeof process === "object" && process.versions && process.versions.node;
      if (NODE_JS) {
        root = global;
      } else if (WEB_WORKER) {
        root = self;
      }
      var COMMON_JS = !root.JS_MD5_NO_COMMON_JS && typeof module === "object" && module.exports;
      var AMD = typeof define === "function" && define.amd;
      var ARRAY_BUFFER = !root.JS_MD5_NO_ARRAY_BUFFER && typeof ArrayBuffer !== "undefined";
      var HEX_CHARS = "0123456789abcdef".split("");
      var EXTRA = [128, 32768, 8388608, -2147483648];
      var SHIFT = [0, 8, 16, 24];
      var OUTPUT_TYPES = ["hex", "array", "digest", "buffer", "arrayBuffer", "base64"];
      var BASE64_ENCODE_CHAR = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split("");
      var blocks = [], buffer8;
      if (ARRAY_BUFFER) {
        var buffer = new ArrayBuffer(68);
        buffer8 = new Uint8Array(buffer);
        blocks = new Uint32Array(buffer);
      }
      var isArray = Array.isArray;
      if (root.JS_MD5_NO_NODE_JS || !isArray) {
        isArray = function(obj) {
          return Object.prototype.toString.call(obj) === "[object Array]";
        };
      }
      var isView = ArrayBuffer.isView;
      if (ARRAY_BUFFER && (root.JS_MD5_NO_ARRAY_BUFFER_IS_VIEW || !isView)) {
        isView = function(obj) {
          return typeof obj === "object" && obj.buffer && obj.buffer.constructor === ArrayBuffer;
        };
      }
      var formatMessage2 = function(message) {
        var type = typeof message;
        if (type === "string") {
          return [message, true];
        }
        if (type !== "object" || message === null) {
          throw new Error(INPUT_ERROR);
        }
        if (ARRAY_BUFFER && message.constructor === ArrayBuffer) {
          return [new Uint8Array(message), false];
        }
        if (!isArray(message) && !isView(message)) {
          throw new Error(INPUT_ERROR);
        }
        return [message, false];
      };
      var createOutputMethod = function(outputType) {
        return function(message) {
          return new Md5(true).update(message)[outputType]();
        };
      };
      var createMethod = function() {
        var method = createOutputMethod("hex");
        if (NODE_JS) {
          method = nodeWrap(method);
        }
        method.create = function() {
          return new Md5();
        };
        method.update = function(message) {
          return method.create().update(message);
        };
        for (var i = 0; i < OUTPUT_TYPES.length; ++i) {
          var type = OUTPUT_TYPES[i];
          method[type] = createOutputMethod(type);
        }
        return method;
      };
      var nodeWrap = function(method) {
        var crypto = require_crypto();
        var Buffer2 = require_buffer().Buffer;
        var bufferFrom;
        if (Buffer2.from && !root.JS_MD5_NO_BUFFER_FROM) {
          bufferFrom = Buffer2.from;
        } else {
          bufferFrom = function(message) {
            return new Buffer2(message);
          };
        }
        var nodeMethod = function(message) {
          if (typeof message === "string") {
            return crypto.createHash("md5").update(message, "utf8").digest("hex");
          } else {
            if (message === null || message === void 0) {
              throw new Error(INPUT_ERROR);
            } else if (message.constructor === ArrayBuffer) {
              message = new Uint8Array(message);
            }
          }
          if (isArray(message) || isView(message) || message.constructor === Buffer2) {
            return crypto.createHash("md5").update(bufferFrom(message)).digest("hex");
          } else {
            return method(message);
          }
        };
        return nodeMethod;
      };
      var createHmacOutputMethod = function(outputType) {
        return function(key, message) {
          return new HmacMd5(key, true).update(message)[outputType]();
        };
      };
      var createHmacMethod = function() {
        var method = createHmacOutputMethod("hex");
        method.create = function(key) {
          return new HmacMd5(key);
        };
        method.update = function(key, message) {
          return method.create(key).update(message);
        };
        for (var i = 0; i < OUTPUT_TYPES.length; ++i) {
          var type = OUTPUT_TYPES[i];
          method[type] = createHmacOutputMethod(type);
        }
        return method;
      };
      function Md5(sharedMemory) {
        if (sharedMemory) {
          blocks[0] = blocks[16] = blocks[1] = blocks[2] = blocks[3] = blocks[4] = blocks[5] = blocks[6] = blocks[7] = blocks[8] = blocks[9] = blocks[10] = blocks[11] = blocks[12] = blocks[13] = blocks[14] = blocks[15] = 0;
          this.blocks = blocks;
          this.buffer8 = buffer8;
        } else {
          if (ARRAY_BUFFER) {
            var buffer2 = new ArrayBuffer(68);
            this.buffer8 = new Uint8Array(buffer2);
            this.blocks = new Uint32Array(buffer2);
          } else {
            this.blocks = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
          }
        }
        this.h0 = this.h1 = this.h2 = this.h3 = this.start = this.bytes = this.hBytes = 0;
        this.finalized = this.hashed = false;
        this.first = true;
      }
      Md5.prototype.update = function(message) {
        if (this.finalized) {
          throw new Error(FINALIZE_ERROR);
        }
        var result = formatMessage2(message);
        message = result[0];
        var isString = result[1];
        var code, index = 0, i, length = message.length, blocks2 = this.blocks;
        var buffer82 = this.buffer8;
        while (index < length) {
          if (this.hashed) {
            this.hashed = false;
            blocks2[0] = blocks2[16];
            blocks2[16] = blocks2[1] = blocks2[2] = blocks2[3] = blocks2[4] = blocks2[5] = blocks2[6] = blocks2[7] = blocks2[8] = blocks2[9] = blocks2[10] = blocks2[11] = blocks2[12] = blocks2[13] = blocks2[14] = blocks2[15] = 0;
          }
          if (isString) {
            if (ARRAY_BUFFER) {
              for (i = this.start; index < length && i < 64; ++index) {
                code = message.charCodeAt(index);
                if (code < 128) {
                  buffer82[i++] = code;
                } else if (code < 2048) {
                  buffer82[i++] = 192 | code >>> 6;
                  buffer82[i++] = 128 | code & 63;
                } else if (code < 55296 || code >= 57344) {
                  buffer82[i++] = 224 | code >>> 12;
                  buffer82[i++] = 128 | code >>> 6 & 63;
                  buffer82[i++] = 128 | code & 63;
                } else {
                  code = 65536 + ((code & 1023) << 10 | message.charCodeAt(++index) & 1023);
                  buffer82[i++] = 240 | code >>> 18;
                  buffer82[i++] = 128 | code >>> 12 & 63;
                  buffer82[i++] = 128 | code >>> 6 & 63;
                  buffer82[i++] = 128 | code & 63;
                }
              }
            } else {
              for (i = this.start; index < length && i < 64; ++index) {
                code = message.charCodeAt(index);
                if (code < 128) {
                  blocks2[i >>> 2] |= code << SHIFT[i++ & 3];
                } else if (code < 2048) {
                  blocks2[i >>> 2] |= (192 | code >>> 6) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code & 63) << SHIFT[i++ & 3];
                } else if (code < 55296 || code >= 57344) {
                  blocks2[i >>> 2] |= (224 | code >>> 12) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code >>> 6 & 63) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code & 63) << SHIFT[i++ & 3];
                } else {
                  code = 65536 + ((code & 1023) << 10 | message.charCodeAt(++index) & 1023);
                  blocks2[i >>> 2] |= (240 | code >>> 18) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code >>> 12 & 63) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code >>> 6 & 63) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code & 63) << SHIFT[i++ & 3];
                }
              }
            }
          } else {
            if (ARRAY_BUFFER) {
              for (i = this.start; index < length && i < 64; ++index) {
                buffer82[i++] = message[index];
              }
            } else {
              for (i = this.start; index < length && i < 64; ++index) {
                blocks2[i >>> 2] |= message[index] << SHIFT[i++ & 3];
              }
            }
          }
          this.lastByteIndex = i;
          this.bytes += i - this.start;
          if (i >= 64) {
            this.start = i - 64;
            this.hash();
            this.hashed = true;
          } else {
            this.start = i;
          }
        }
        if (this.bytes > 4294967295) {
          this.hBytes += this.bytes / 4294967296 << 0;
          this.bytes = this.bytes % 4294967296;
        }
        return this;
      };
      Md5.prototype.finalize = function() {
        if (this.finalized) {
          return;
        }
        this.finalized = true;
        var blocks2 = this.blocks, i = this.lastByteIndex;
        blocks2[i >>> 2] |= EXTRA[i & 3];
        if (i >= 56) {
          if (!this.hashed) {
            this.hash();
          }
          blocks2[0] = blocks2[16];
          blocks2[16] = blocks2[1] = blocks2[2] = blocks2[3] = blocks2[4] = blocks2[5] = blocks2[6] = blocks2[7] = blocks2[8] = blocks2[9] = blocks2[10] = blocks2[11] = blocks2[12] = blocks2[13] = blocks2[14] = blocks2[15] = 0;
        }
        blocks2[14] = this.bytes << 3;
        blocks2[15] = this.hBytes << 3 | this.bytes >>> 29;
        this.hash();
      };
      Md5.prototype.hash = function() {
        var a, b, c, d, bc, da, blocks2 = this.blocks;
        if (this.first) {
          a = blocks2[0] - 680876937;
          a = (a << 7 | a >>> 25) - 271733879 << 0;
          d = (-1732584194 ^ a & 2004318071) + blocks2[1] - 117830708;
          d = (d << 12 | d >>> 20) + a << 0;
          c = (-271733879 ^ d & (a ^ -271733879)) + blocks2[2] - 1126478375;
          c = (c << 17 | c >>> 15) + d << 0;
          b = (a ^ c & (d ^ a)) + blocks2[3] - 1316259209;
          b = (b << 22 | b >>> 10) + c << 0;
        } else {
          a = this.h0;
          b = this.h1;
          c = this.h2;
          d = this.h3;
          a += (d ^ b & (c ^ d)) + blocks2[0] - 680876936;
          a = (a << 7 | a >>> 25) + b << 0;
          d += (c ^ a & (b ^ c)) + blocks2[1] - 389564586;
          d = (d << 12 | d >>> 20) + a << 0;
          c += (b ^ d & (a ^ b)) + blocks2[2] + 606105819;
          c = (c << 17 | c >>> 15) + d << 0;
          b += (a ^ c & (d ^ a)) + blocks2[3] - 1044525330;
          b = (b << 22 | b >>> 10) + c << 0;
        }
        a += (d ^ b & (c ^ d)) + blocks2[4] - 176418897;
        a = (a << 7 | a >>> 25) + b << 0;
        d += (c ^ a & (b ^ c)) + blocks2[5] + 1200080426;
        d = (d << 12 | d >>> 20) + a << 0;
        c += (b ^ d & (a ^ b)) + blocks2[6] - 1473231341;
        c = (c << 17 | c >>> 15) + d << 0;
        b += (a ^ c & (d ^ a)) + blocks2[7] - 45705983;
        b = (b << 22 | b >>> 10) + c << 0;
        a += (d ^ b & (c ^ d)) + blocks2[8] + 1770035416;
        a = (a << 7 | a >>> 25) + b << 0;
        d += (c ^ a & (b ^ c)) + blocks2[9] - 1958414417;
        d = (d << 12 | d >>> 20) + a << 0;
        c += (b ^ d & (a ^ b)) + blocks2[10] - 42063;
        c = (c << 17 | c >>> 15) + d << 0;
        b += (a ^ c & (d ^ a)) + blocks2[11] - 1990404162;
        b = (b << 22 | b >>> 10) + c << 0;
        a += (d ^ b & (c ^ d)) + blocks2[12] + 1804603682;
        a = (a << 7 | a >>> 25) + b << 0;
        d += (c ^ a & (b ^ c)) + blocks2[13] - 40341101;
        d = (d << 12 | d >>> 20) + a << 0;
        c += (b ^ d & (a ^ b)) + blocks2[14] - 1502002290;
        c = (c << 17 | c >>> 15) + d << 0;
        b += (a ^ c & (d ^ a)) + blocks2[15] + 1236535329;
        b = (b << 22 | b >>> 10) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[1] - 165796510;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[6] - 1069501632;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[11] + 643717713;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[0] - 373897302;
        b = (b << 20 | b >>> 12) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[5] - 701558691;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[10] + 38016083;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[15] - 660478335;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[4] - 405537848;
        b = (b << 20 | b >>> 12) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[9] + 568446438;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[14] - 1019803690;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[3] - 187363961;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[8] + 1163531501;
        b = (b << 20 | b >>> 12) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[13] - 1444681467;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[2] - 51403784;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[7] + 1735328473;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[12] - 1926607734;
        b = (b << 20 | b >>> 12) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[5] - 378558;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[8] - 2022574463;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[11] + 1839030562;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[14] - 35309556;
        b = (b << 23 | b >>> 9) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[1] - 1530992060;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[4] + 1272893353;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[7] - 155497632;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[10] - 1094730640;
        b = (b << 23 | b >>> 9) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[13] + 681279174;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[0] - 358537222;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[3] - 722521979;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[6] + 76029189;
        b = (b << 23 | b >>> 9) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[9] - 640364487;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[12] - 421815835;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[15] + 530742520;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[2] - 995338651;
        b = (b << 23 | b >>> 9) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[0] - 198630844;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[7] + 1126891415;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[14] - 1416354905;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[5] - 57434055;
        b = (b << 21 | b >>> 11) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[12] + 1700485571;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[3] - 1894986606;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[10] - 1051523;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[1] - 2054922799;
        b = (b << 21 | b >>> 11) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[8] + 1873313359;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[15] - 30611744;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[6] - 1560198380;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[13] + 1309151649;
        b = (b << 21 | b >>> 11) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[4] - 145523070;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[11] - 1120210379;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[2] + 718787259;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[9] - 343485551;
        b = (b << 21 | b >>> 11) + c << 0;
        if (this.first) {
          this.h0 = a + 1732584193 << 0;
          this.h1 = b - 271733879 << 0;
          this.h2 = c - 1732584194 << 0;
          this.h3 = d + 271733878 << 0;
          this.first = false;
        } else {
          this.h0 = this.h0 + a << 0;
          this.h1 = this.h1 + b << 0;
          this.h2 = this.h2 + c << 0;
          this.h3 = this.h3 + d << 0;
        }
      };
      Md5.prototype.hex = function() {
        this.finalize();
        var h0 = this.h0, h1 = this.h1, h2 = this.h2, h3 = this.h3;
        return HEX_CHARS[h0 >>> 4 & 15] + HEX_CHARS[h0 & 15] + HEX_CHARS[h0 >>> 12 & 15] + HEX_CHARS[h0 >>> 8 & 15] + HEX_CHARS[h0 >>> 20 & 15] + HEX_CHARS[h0 >>> 16 & 15] + HEX_CHARS[h0 >>> 28 & 15] + HEX_CHARS[h0 >>> 24 & 15] + HEX_CHARS[h1 >>> 4 & 15] + HEX_CHARS[h1 & 15] + HEX_CHARS[h1 >>> 12 & 15] + HEX_CHARS[h1 >>> 8 & 15] + HEX_CHARS[h1 >>> 20 & 15] + HEX_CHARS[h1 >>> 16 & 15] + HEX_CHARS[h1 >>> 28 & 15] + HEX_CHARS[h1 >>> 24 & 15] + HEX_CHARS[h2 >>> 4 & 15] + HEX_CHARS[h2 & 15] + HEX_CHARS[h2 >>> 12 & 15] + HEX_CHARS[h2 >>> 8 & 15] + HEX_CHARS[h2 >>> 20 & 15] + HEX_CHARS[h2 >>> 16 & 15] + HEX_CHARS[h2 >>> 28 & 15] + HEX_CHARS[h2 >>> 24 & 15] + HEX_CHARS[h3 >>> 4 & 15] + HEX_CHARS[h3 & 15] + HEX_CHARS[h3 >>> 12 & 15] + HEX_CHARS[h3 >>> 8 & 15] + HEX_CHARS[h3 >>> 20 & 15] + HEX_CHARS[h3 >>> 16 & 15] + HEX_CHARS[h3 >>> 28 & 15] + HEX_CHARS[h3 >>> 24 & 15];
      };
      Md5.prototype.toString = Md5.prototype.hex;
      Md5.prototype.digest = function() {
        this.finalize();
        var h0 = this.h0, h1 = this.h1, h2 = this.h2, h3 = this.h3;
        return [
          h0 & 255,
          h0 >>> 8 & 255,
          h0 >>> 16 & 255,
          h0 >>> 24 & 255,
          h1 & 255,
          h1 >>> 8 & 255,
          h1 >>> 16 & 255,
          h1 >>> 24 & 255,
          h2 & 255,
          h2 >>> 8 & 255,
          h2 >>> 16 & 255,
          h2 >>> 24 & 255,
          h3 & 255,
          h3 >>> 8 & 255,
          h3 >>> 16 & 255,
          h3 >>> 24 & 255
        ];
      };
      Md5.prototype.array = Md5.prototype.digest;
      Md5.prototype.arrayBuffer = function() {
        this.finalize();
        var buffer2 = new ArrayBuffer(16);
        var blocks2 = new Uint32Array(buffer2);
        blocks2[0] = this.h0;
        blocks2[1] = this.h1;
        blocks2[2] = this.h2;
        blocks2[3] = this.h3;
        return buffer2;
      };
      Md5.prototype.buffer = Md5.prototype.arrayBuffer;
      Md5.prototype.base64 = function() {
        var v1, v2, v3, base64Str = "", bytes = this.array();
        for (var i = 0; i < 15; ) {
          v1 = bytes[i++];
          v2 = bytes[i++];
          v3 = bytes[i++];
          base64Str += BASE64_ENCODE_CHAR[v1 >>> 2] + BASE64_ENCODE_CHAR[(v1 << 4 | v2 >>> 4) & 63] + BASE64_ENCODE_CHAR[(v2 << 2 | v3 >>> 6) & 63] + BASE64_ENCODE_CHAR[v3 & 63];
        }
        v1 = bytes[i];
        base64Str += BASE64_ENCODE_CHAR[v1 >>> 2] + BASE64_ENCODE_CHAR[v1 << 4 & 63] + "==";
        return base64Str;
      };
      function HmacMd5(key, sharedMemory) {
        var i, result = formatMessage2(key);
        key = result[0];
        if (result[1]) {
          var bytes = [], length = key.length, index = 0, code;
          for (i = 0; i < length; ++i) {
            code = key.charCodeAt(i);
            if (code < 128) {
              bytes[index++] = code;
            } else if (code < 2048) {
              bytes[index++] = 192 | code >>> 6;
              bytes[index++] = 128 | code & 63;
            } else if (code < 55296 || code >= 57344) {
              bytes[index++] = 224 | code >>> 12;
              bytes[index++] = 128 | code >>> 6 & 63;
              bytes[index++] = 128 | code & 63;
            } else {
              code = 65536 + ((code & 1023) << 10 | key.charCodeAt(++i) & 1023);
              bytes[index++] = 240 | code >>> 18;
              bytes[index++] = 128 | code >>> 12 & 63;
              bytes[index++] = 128 | code >>> 6 & 63;
              bytes[index++] = 128 | code & 63;
            }
          }
          key = bytes;
        }
        if (key.length > 64) {
          key = new Md5(true).update(key).array();
        }
        var oKeyPad = [], iKeyPad = [];
        for (i = 0; i < 64; ++i) {
          var b = key[i] || 0;
          oKeyPad[i] = 92 ^ b;
          iKeyPad[i] = 54 ^ b;
        }
        Md5.call(this, sharedMemory);
        this.update(iKeyPad);
        this.oKeyPad = oKeyPad;
        this.inner = true;
        this.sharedMemory = sharedMemory;
      }
      HmacMd5.prototype = new Md5();
      HmacMd5.prototype.finalize = function() {
        Md5.prototype.finalize.call(this);
        if (this.inner) {
          this.inner = false;
          var innerHash = this.array();
          Md5.call(this, this.sharedMemory);
          this.update(this.oKeyPad);
          this.update(innerHash);
          Md5.prototype.finalize.call(this);
        }
      };
      var exports2 = createMethod();
      exports2.md5 = exports2;
      exports2.md5.hmac = createHmacMethod();
      if (COMMON_JS) {
        module.exports = exports2;
      } else {
        root.md5 = exports2;
        if (AMD) {
          define(function() {
            return exports2;
          });
        }
      }
    })();
  }
});

// src/core/video.js
var BVID_RE = /(BV[0-9A-Za-z]{10,})/;
function extractBvid(input) {
  if (!input) return "";
  const match = String(input).match(BVID_RE);
  return match ? match[1] : "";
}
function getUrlPage(input) {
  if (!input) return 1;
  try {
    const url = new URL(String(input));
    const page = Number(url.searchParams.get("p") || url.searchParams.get("page") || 1);
    return Number.isFinite(page) && page > 0 ? Math.floor(page) : 1;
  } catch (_error) {
    return 1;
  }
}
function safeFilenamePart(input, fallback = "bilibili-comments") {
  const safe = String(input || "").replace(/[\\/:*?"<>|]+/g, "_").replace(/[\u0000-\u001f\u007f]+/g, "").replace(/\s+/g, " ").trim().replace(/^\.+|\.+$/g, "").trim();
  return safe || fallback;
}
function makeDownloadFilename(options = {}) {
  const bvid = safeFilenamePart(options.bvid || "bilibili", "bilibili");
  const title = safeFilenamePart(options.title || "comments", "comments");
  const extension = safeFilenamePart(String(options.extension || "json").replace(/^\.+/, ""), "json").toLowerCase();
  const generatedAt = options.generatedAt ? new Date(options.generatedAt) : /* @__PURE__ */ new Date();
  const stamp = Number.isFinite(generatedAt.getTime()) ? generatedAt.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "").replace("T", "-") : (/* @__PURE__ */ new Date()).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "").replace("T", "-");
  return `${bvid}-${title}-${stamp}.${extension}`;
}

// src/extension/sidepanel/i18n.js
var UI_LOCALE_STORAGE_KEY = "uiLocale";
var DEFAULT_LOCALE = "en";
var ZH_LOCALE = "zh";
var messages = {
  en: {
    "action.aiAnalysis": "AI Analysis",
    "action.copyAll": "Copy All",
    "action.exportJson": "Export JSON",
    "action.exportMarkdown": "Export Markdown",
    "action.refresh": "Refresh",
    "action.refreshActiveVideo": "Detect current tab again",
    "action.startCapture": "Start Capture",
    "action.stop": "Stop",
    "active.currentVideoPage": "Current video page",
    "active.loadingMeta": "Waiting for page info",
    "active.loadingTitle": "Reading current tab",
    "active.missingMeta": "Switch to a video page, then refresh",
    "active.missingTitle": "Current tab is not a Bilibili video",
    "active.openVideo": "Open a Bilibili video page first",
    "app.title": "Bilibili Comment Export Helper",
    "capture.includeReplies": "Enable capture",
    "capture.noItemLimit": "No comment limit",
    "capture.noPageLimit": "No page limit",
    "capture.noReplyLimit": "No reply limit",
    "capture.noRoundLimit": "No round limit",
    "capture.replyExpandRounds": "Max pages",
    "capture.replyKeepCount": "Max replies",
    "capture.replies": "Nested Replies",
    "capture.replyOrder": "Nested reply order",
    "capture.root": "Main Comments",
    "capture.rootKeepCount": "Max comments",
    "capture.rootLoadRounds": "Max loads",
    "capture.rootOrder": "Main comment order",
    "capture.scope": "Comment capture",
    "capture.summaryAllItems": "No comment limit",
    "capture.summaryAllLoads": "No round limit",
    "capture.summaryItems": "Keep {count}",
    "capture.summaryLoads": "First {count} loads",
    "capture.title": "Capture Conditions",
    "comment.metrics": "{time} \xB7 {likes} likes \xB7 {replies} replies",
    "copy.done": "Copied all",
    "empty.noComments": "No comments captured.",
    "empty.noMatches": 'No comments contain "{query}".',
    "error.captureFailed": "Capture failed.",
    "error.needVideo": "Switch to a Bilibili video page first.",
    "error.openAnalysis": "Unable to open AI analysis page.",
    "nav.language": "Interface language",
    "nav.views": "Feature switch",
    "order.default": "Default Order",
    "order.latest": "Latest",
    "order.timeDesc": "Time Desc",
    "progress.done": "Capture complete",
    "progress.failed": "Capture failed",
    "progress.readVideo": "Reading video info",
    "progress.replies": "Replies {current}/{total}",
    "progress.root": "Main comments load {page} \xB7 collected {count}",
    "progress.running": "Running",
    "progress.start": "Preparing comment capture",
    "progress.stopped": "Capture stopped",
    "progress.waiting": "Waiting",
    "thread.pinned": "Pinned",
    "results.emptyList": "Captured comments will appear here as compact text.",
    "results.emptyMeta": "Result source appears after capture",
    "results.emptyTitle": "No result",
    "results.notCaptured": "Not captured yet",
    "results.scope": "This result",
    "results.stats": "{pinned}{roots} main \xB7 {replies} replies",
    "results.statsPinned": "{count} pinned \xB7 ",
    "results.title": "Results",
    "results.untitledVideo": "Untitled video",
    "search.comments": "Search comments",
    "status.exportedJson": "Exported JSON",
    "status.exportedMarkdown": "Exported Markdown",
    "tab.capture": "Capture",
    "tab.results": "Results"
  },
  zh: {
    "action.aiAnalysis": "AI\u5206\u6790",
    "action.copyAll": "\u590D\u5236\u5168\u90E8",
    "action.exportJson": "\u5BFC\u51FA JSON",
    "action.exportMarkdown": "\u5BFC\u51FA Markdown",
    "action.refresh": "\u91CD\u65B0\u8BC6\u522B",
    "action.refreshActiveVideo": "\u91CD\u65B0\u8BC6\u522B\u5F53\u524D\u6807\u7B7E\u9875",
    "action.startCapture": "\u5F00\u59CB\u6293\u53D6\u8BC4\u8BBA",
    "action.stop": "\u505C\u6B62",
    "active.currentVideoPage": "\u5F53\u524D\u89C6\u9891\u9875",
    "active.loadingMeta": "\u7B49\u5F85\u9875\u9762\u4FE1\u606F",
    "active.loadingTitle": "\u8BFB\u53D6\u5F53\u524D\u6807\u7B7E\u9875",
    "active.missingMeta": "\u5207\u6362\u5230\u89C6\u9891\u9875\u540E\u5237\u65B0",
    "active.missingTitle": "\u5F53\u524D\u6807\u7B7E\u9875\u4E0D\u662F B \u7AD9\u89C6\u9891",
    "active.openVideo": "\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A B \u7AD9\u89C6\u9891\u9875",
    "app.title": "B\u7AD9\u8BC4\u8BBA\u5BFC\u51FA\u52A9\u624B",
    "capture.includeReplies": "\u542F\u7528\u6293\u53D6",
    "capture.noItemLimit": "\u4E0D\u9650\u5236\u6761\u6570",
    "capture.noPageLimit": "\u4E0D\u9650\u5236\u9875\u6570",
    "capture.noReplyLimit": "\u4E0D\u9650\u5236\u56DE\u590D\u6570",
    "capture.noRoundLimit": "\u4E0D\u9650\u5236\u8F6E\u6570",
    "capture.replyExpandRounds": "\u6700\u591A\u5C55\u5F00\u9875\u6570",
    "capture.replyKeepCount": "\u6700\u591A\u4FDD\u7559\u56DE\u590D\u6570",
    "capture.replies": "\u697C\u4E2D\u697C",
    "capture.replyOrder": "\u697C\u4E2D\u697C\u6392\u5E8F",
    "capture.root": "\u4E3B\u8BC4\u8BBA",
    "capture.rootKeepCount": "\u6700\u591A\u4FDD\u7559\u6761\u6570",
    "capture.rootLoadRounds": "\u6700\u591A\u52A0\u8F7D\u8F6E\u6570",
    "capture.rootOrder": "\u4E3B\u8BC4\u8BBA\u6392\u5E8F",
    "capture.scope": "\u8BC4\u8BBA\u6293\u53D6",
    "capture.summaryAllItems": "\u4E0D\u9650\u5236\u6761\u6570",
    "capture.summaryAllLoads": "\u4E0D\u9650\u5236\u8F6E\u6570",
    "capture.summaryItems": "\u4FDD\u7559 {count} \u6761",
    "capture.summaryLoads": "\u524D {count} \u8F6E",
    "capture.title": "\u6293\u53D6\u6761\u4EF6",
    "comment.metrics": "{time} \xB7 {likes}\u8D5E \xB7 {replies}\u56DE\u590D",
    "copy.done": "\u5DF2\u590D\u5236\u5168\u90E8",
    "empty.noComments": "\u6CA1\u6709\u6293\u53D6\u5230\u8BC4\u8BBA\u3002",
    "empty.noMatches": "\u6CA1\u6709\u627E\u5230\u5305\u542B\u201C{query}\u201D\u7684\u8BC4\u8BBA\u3002",
    "error.captureFailed": "\u6293\u53D6\u5931\u8D25\u3002",
    "error.needVideo": "\u8BF7\u5148\u5207\u6362\u5230\u54D4\u54E9\u54D4\u54E9\u89C6\u9891\u9875\u3002",
    "error.openAnalysis": "\u65E0\u6CD5\u6253\u5F00 AI \u5206\u6790\u9875\u9762\u3002",
    "nav.language": "\u754C\u9762\u8BED\u8A00",
    "nav.views": "\u529F\u80FD\u5207\u6362",
    "order.default": "\u9ED8\u8BA4\u987A\u5E8F",
    "order.latest": "\u6700\u65B0",
    "order.timeDesc": "\u65F6\u95F4\u5012\u5E8F",
    "progress.done": "\u6293\u53D6\u5B8C\u6210",
    "progress.failed": "\u6293\u53D6\u5931\u8D25",
    "progress.readVideo": "\u8BFB\u53D6\u89C6\u9891\u4FE1\u606F",
    "progress.replies": "\u697C\u4E2D\u697C {current}/{total}",
    "progress.root": "\u4E3B\u8BC4\u8BBA\u7B2C {page} \u8F6E \xB7 \u5DF2\u6536\u96C6 {count} \u6761",
    "progress.running": "\u8FD0\u884C\u4E2D",
    "progress.start": "\u51C6\u5907\u6293\u53D6\u8BC4\u8BBA",
    "progress.stopped": "\u5DF2\u505C\u6B62\u6293\u53D6",
    "progress.waiting": "\u7B49\u5F85\u4EFB\u52A1",
    "thread.pinned": "\u7F6E\u9876",
    "results.emptyList": "\u6293\u53D6\u5B8C\u6210\u540E\uFF0C\u8BC4\u8BBA\u4F1A\u5728\u8FD9\u91CC\u4EE5\u7D27\u51D1\u6587\u672C\u663E\u793A\u3002",
    "results.emptyMeta": "\u6293\u53D6\u5B8C\u6210\u540E\u4F1A\u663E\u793A\u672C\u6B21\u7ED3\u679C\u6765\u6E90",
    "results.emptyTitle": "\u6682\u65E0\u7ED3\u679C",
    "results.notCaptured": "\u5C1A\u672A\u6293\u53D6",
    "results.scope": "\u672C\u6B21\u7ED3\u679C",
    "results.stats": "{pinned}{roots} \u4E3B\u8BC4\u8BBA \xB7 {replies} \u697C\u4E2D\u697C",
    "results.statsPinned": "{count} \u7F6E\u9876 \xB7 ",
    "results.title": "\u67E5\u770B\u7ED3\u679C",
    "results.untitledVideo": "\u672A\u547D\u540D\u89C6\u9891",
    "search.comments": "\u641C\u7D22\u8BC4\u8BBA",
    "status.exportedJson": "\u5DF2\u5BFC\u51FA JSON",
    "status.exportedMarkdown": "\u5DF2\u5BFC\u51FA Markdown",
    "tab.capture": "\u6293\u53D6\u8BC4\u8BBA",
    "tab.results": "\u67E5\u770B\u7ED3\u679C"
  }
};
var currentLocale = ZH_LOCALE;
async function loadUiLocale(storage, languages = navigator.languages) {
  const stored = await storage.get([UI_LOCALE_STORAGE_KEY]);
  currentLocale = normalizeLocale(stored[UI_LOCALE_STORAGE_KEY]) || pickLocale(languages);
  return currentLocale;
}
async function saveUiLocale(storage, locale) {
  currentLocale = normalizeLocale(locale) || ZH_LOCALE;
  await storage.set({ [UI_LOCALE_STORAGE_KEY]: currentLocale });
  return currentLocale;
}
function applyLocale(elements2, locale = currentLocale) {
  currentLocale = normalizeLocale(locale) || ZH_LOCALE;
  document.documentElement.lang = currentLocale === ZH_LOCALE ? "zh-CN" : "en";
  document.title = t("app.title");
  for (const node of document.querySelectorAll("[data-i18n]")) {
    node.textContent = t(node.dataset.i18n);
  }
  for (const node of document.querySelectorAll("[data-i18n-placeholder]")) {
    node.placeholder = t(node.dataset.i18nPlaceholder);
  }
  for (const node of document.querySelectorAll("[data-i18n-aria]")) {
    node.setAttribute("aria-label", t(node.dataset.i18nAria));
  }
  for (const node of document.querySelectorAll("[data-i18n-title]")) {
    node.title = t(node.dataset.i18nTitle);
  }
  for (const button of elements2.localeButtons || []) {
    const isActive = button.dataset.localeOption === currentLocale;
    button.classList.toggle("is-active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  }
}
function t(key, params = {}) {
  const dictionary = messages[currentLocale] || messages[ZH_LOCALE];
  const template = dictionary[key] || messages.en[key] || messages.zh[key] || key;
  return formatMessage(template, params);
}
function pickLocale(languages = []) {
  const list = Array.isArray(languages) ? languages : [languages];
  for (const language of list) {
    const locale = normalizeLocale(language);
    if (locale) return locale;
  }
  return DEFAULT_LOCALE;
}
function normalizeLocale(language) {
  const value = String(language || "").trim().toLowerCase();
  if (!value) return "";
  return value.startsWith("zh") ? ZH_LOCALE : DEFAULT_LOCALE;
}
function formatMessage(template, params) {
  return String(template).replace(
    /\{([a-zA-Z0-9_]+)\}/g,
    (match, name) => Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match
  );
}

// src/extension/sidepanel/active-video.js
var activeVideoDetectionTimer = null;
var activeVideoDetectionSeq = 0;
function watchActiveVideoTabs(chromeApi, detect) {
  chromeApi.tabs?.onActivated?.addListener(() => scheduleActiveVideoDetection(detect));
  chromeApi.tabs?.onUpdated?.addListener((_tabId, changeInfo) => {
    if (changeInfo.status === "complete" || changeInfo.url) scheduleActiveVideoDetection(detect);
  });
}
function scheduleActiveVideoDetection(detect) {
  clearTimeout(activeVideoDetectionTimer);
  activeVideoDetectionTimer = setTimeout(detect, 120);
}
async function detectActiveVideoTab(chromeApi, hooks) {
  const seq = ++activeVideoDetectionSeq;
  hooks.onLoading();
  const [tab] = await chromeApi.tabs.query({ active: true, currentWindow: true });
  if (seq !== activeVideoDetectionSeq) return;
  if (!tab?.id) {
    hooks.onMissing(t("active.openVideo"));
    return;
  }
  const pageUrl = tab.url || "";
  const urlBvid = isBilibiliVideoPage(pageUrl) ? extractBvid(pageUrl) : "";
  if (urlBvid) {
    hooks.onReady(toActiveVideo({ title: tab.title, url: pageUrl, bvid: urlBvid, tabId: tab.id }));
    return;
  }
  if (!isBilibiliVideoPage(pageUrl)) {
    hooks.onMissing(tab.title);
    return;
  }
  try {
    const context = await chromeApi.tabs.sendMessage(tab.id, { type: "GET_BILI_PAGE_CONTEXT" });
    if (seq !== activeVideoDetectionSeq) return;
    if (context?.ok && context.bvid) {
      hooks.onReady(toActiveVideo({ ...context, tabId: tab.id }));
      return;
    }
  } catch (_error) {
  }
  if (seq !== activeVideoDetectionSeq) return;
  hooks.onMissing(tab.title);
}
function isBilibiliVideoPage(input) {
  try {
    const url = new URL(input);
    return url.hostname === "www.bilibili.com" && url.pathname.startsWith("/video/");
  } catch (_error) {
    return false;
  }
}
function toActiveVideo(context) {
  return {
    title: cleanTitle(context.title || "\u54D4\u54E9\u54D4\u54E9\u89C6\u9891"),
    url: context.url || "",
    bvid: context.bvid || extractBvid(context.url),
    tabId: context.tabId || null
  };
}
function cleanTitle(title) {
  return String(title).replace(/_哔哩哔哩_bilibili$/i, "").trim();
}

// src/extension/sidepanel/analysis-target.js
function selectAiAnalysisTarget({ activeVideo, latestCaptureResult } = {}) {
  if (latestCaptureResult?.video?.bvid) {
    return {
      bvid: latestCaptureResult.video.bvid,
      url: latestCaptureResult.source?.pageUrl || latestCaptureResult.video.url || activeVideo?.url || "",
      video: latestCaptureResult.video
    };
  }
  if (activeVideo?.bvid) {
    return {
      bvid: activeVideo.bvid,
      url: activeVideo.url || "",
      video: activeVideo
    };
  }
  return null;
}

// src/core/site-link.js
var SITE_RESULT_URL = "https://danmu.liu-qi.cn/result";
var SITE_RESULT_SOURCE = "bilibili-comment-capture";
var SITE_RESULT_ANALYSIS = "comments";
function buildSiteResultUrl(options = {}) {
  const video = options.video || null;
  const bvid = options.bvid || extractBvid(options.url) || video?.bvid || "";
  if (!bvid) {
    throw new Error("No BV id found for site analysis page");
  }
  const target = new URL(options.siteBaseUrl || SITE_RESULT_URL);
  target.searchParams.set("bvid", bvid);
  target.searchParams.set("source", options.source || SITE_RESULT_SOURCE);
  target.searchParams.set("analysis", options.analysis || SITE_RESULT_ANALYSIS);
  const cid = options.cid || video?.cid || video?.page?.cid;
  if (cid) {
    target.searchParams.set("cid", String(cid));
  }
  const videoPage = typeof video?.page === "object" ? video.page.page : video?.page;
  const page = options.page || videoPage || getUrlPage(options.url);
  if (page) {
    target.searchParams.set("p", String(page));
  }
  return target.toString();
}

// src/core/wbi.js
var import_js_md5 = __toESM(require_md5(), 1);

// src/core/model.js
function flattenComments(comments, options = {}) {
  const rows = [];
  for (const comment of comments || []) {
    const section = comment.source?.section || options.section || "normal";
    rows.push(toFlatRow(comment, "root", { section, path: [comment.id].filter(Boolean) }));
    for (const reply of comment.replies || []) {
      rows.push(toFlatRow(reply, "reply", {
        section: reply.source?.section || "reply",
        path: [comment.id, reply.id].filter(Boolean)
      }));
    }
  }
  return rows;
}
function toFlatRow(comment, level, context = {}) {
  return {
    section: context.section || comment.source?.section || (level === "reply" ? "reply" : "normal"),
    level,
    id: comment.id,
    rootId: comment.rootId || (level === "reply" ? comment.rootId : null),
    parentId: comment.parentId || null,
    path: context.path || [comment.id].filter(Boolean),
    author: comment.author,
    content: comment.content,
    metrics: comment.metrics,
    createdAt: comment.createdAt,
    ctime: comment.ctime,
    floor: comment.floor,
    source: comment.source
  };
}

// src/core/capture.js
var DEFAULT_CAPTURE_OPTIONS = {
  rootOrder: "default",
  rootMaxPages: 20,
  rootMaxItems: 100,
  includeReplies: true,
  replyOrder: "default",
  replyMaxPagesPerRoot: 1,
  replyMaxItemsPerRoot: 5,
  requestDelayMs: 150
};
var ORDER_VALUES = /* @__PURE__ */ new Set(["default", "latest"]);
function normalizeCaptureOptions(input = {}) {
  return {
    rootOrder: normalizeOrder(input.rootOrder, DEFAULT_CAPTURE_OPTIONS.rootOrder),
    rootMaxPages: normalizeLimit(input.rootMaxPages, DEFAULT_CAPTURE_OPTIONS.rootMaxPages, { min: 1, max: 5e3 }),
    rootMaxItems: normalizeLimit(input.rootMaxItems, DEFAULT_CAPTURE_OPTIONS.rootMaxItems, { min: 1, max: 1e6 }),
    includeReplies: input.includeReplies !== false,
    replyOrder: normalizeOrder(input.replyOrder, DEFAULT_CAPTURE_OPTIONS.replyOrder),
    replyMaxPagesPerRoot: normalizeLimit(input.replyMaxPagesPerRoot, DEFAULT_CAPTURE_OPTIONS.replyMaxPagesPerRoot, {
      min: 1,
      max: 500
    }),
    replyMaxItemsPerRoot: normalizeLimit(input.replyMaxItemsPerRoot, DEFAULT_CAPTURE_OPTIONS.replyMaxItemsPerRoot, {
      min: 0,
      max: 1e5
    }),
    requestDelayMs: normalizeFiniteNumber(input.requestDelayMs, DEFAULT_CAPTURE_OPTIONS.requestDelayMs, {
      min: 0,
      max: 5e3
    })
  };
}
function normalizeLimit(value, fallback, bounds) {
  if (value === "all" || value === Infinity) return Infinity;
  return normalizeFiniteNumber(value, fallback, bounds);
}
function normalizeOrder(value, fallback) {
  if (ORDER_VALUES.has(value)) return value;
  return fallback;
}
function normalizeFiniteNumber(value, fallback, bounds) {
  const number = Number(value ?? fallback);
  const finite = Number.isFinite(number) ? Math.floor(number) : fallback;
  return Math.min(bounds.max, Math.max(bounds.min, finite));
}
function serializeCaptureOptions(options) {
  const serialized = {};
  for (const [key, value] of Object.entries(options)) {
    serialized[key] = value === Infinity ? "all" : value;
  }
  return serialized;
}

// src/extension/sidepanel/capture-options-form.js
var OPTION_STORAGE_KEY = "captureOptions";
var captureOptions = normalizeCaptureOptions();
function bindCaptureOptionEvents(elements2, onChange) {
  for (const input of document.querySelectorAll("#view-capture input")) {
    input.addEventListener("input", onChange);
    input.addEventListener("change", onChange);
  }
}
async function loadCaptureOptions(storage, elements2) {
  const stored = await storage.get([OPTION_STORAGE_KEY]);
  captureOptions = normalizeCaptureOptions(stored[OPTION_STORAGE_KEY] || {});
  applyCaptureOptions(elements2, captureOptions);
}
async function saveCaptureOptions(storage, elements2) {
  const options = readCaptureOptionsFromForm(elements2);
  await storage.set({ [OPTION_STORAGE_KEY]: options });
  return options;
}
function readCaptureOptionsFromForm(elements2) {
  captureOptions = normalizeCaptureOptions({
    ...captureOptions,
    rootOrder: getRadioValue("root-order"),
    rootMaxPages: readLimit(elements2.rootLoads, elements2.rootLoadsAll),
    rootMaxItems: readLimit(elements2.rootItems, elements2.rootItemsAll),
    includeReplies: elements2.includeReplies.checked,
    replyOrder: getRadioValue("reply-order"),
    replyMaxPagesPerRoot: readLimit(elements2.replyLoads, elements2.replyLoadsAll),
    replyMaxItemsPerRoot: readLimit(elements2.replyItems, elements2.replyItemsAll)
  });
  return serializeCaptureOptions(captureOptions);
}
function syncCaptureLimitInputs(elements2) {
  const repliesEnabled = elements2.includeReplies.checked;
  elements2.replyOptionsPanel?.classList.toggle("is-disabled", !repliesEnabled);
  elements2.replyOptionsPanel?.setAttribute("aria-disabled", repliesEnabled ? "false" : "true");
  for (const input of elements2.replyOptionControls || []) {
    input.disabled = !repliesEnabled;
  }
  for (const [input, checkbox, groupEnabled] of [
    [elements2.rootLoads, elements2.rootLoadsAll, true],
    [elements2.rootItems, elements2.rootItemsAll, true],
    [elements2.replyLoads, elements2.replyLoadsAll, repliesEnabled],
    [elements2.replyItems, elements2.replyItemsAll, repliesEnabled]
  ]) {
    input.disabled = !groupEnabled || checkbox.checked;
  }
}
function setCaptureOptionsLocked(elements2, locked) {
  if (locked) {
    for (const input of elements2.captureOptionControls || []) {
      input.disabled = true;
    }
    return;
  }
  syncCaptureLimitInputs(elements2);
}
function updateCaptureSummary(elements2) {
  const loads = elements2.rootLoadsAll.checked ? t("capture.summaryAllLoads") : t("capture.summaryLoads", { count: elements2.rootLoads.value || 1 });
  const items = elements2.rootItemsAll.checked ? t("capture.summaryAllItems") : t("capture.summaryItems", { count: elements2.rootItems.value || 1 });
  elements2.captureSummary.textContent = `${loads} \xB7 ${items}`;
}
function applyCaptureOptions(elements2, options) {
  setRadioValue("root-order", options.rootOrder);
  setRadioValue("reply-order", options.replyOrder);
  setLimit(elements2.rootLoads, elements2.rootLoadsAll, options.rootMaxPages);
  setLimit(elements2.rootItems, elements2.rootItemsAll, options.rootMaxItems);
  setLimit(elements2.replyLoads, elements2.replyLoadsAll, options.replyMaxPagesPerRoot);
  setLimit(elements2.replyItems, elements2.replyItemsAll, options.replyMaxItemsPerRoot);
  elements2.includeReplies.checked = options.includeReplies !== false;
}
function readLimit(input, checkbox) {
  return checkbox.checked ? "all" : Number(input.value);
}
function setLimit(input, checkbox, value) {
  checkbox.checked = value === "all" || value === Infinity;
  if (!checkbox.checked) input.value = String(value);
}
function getRadioValue(name) {
  return document.querySelector(`input[name="${name}"]:checked`)?.value || "";
}
function setRadioValue(name, value) {
  const input = document.querySelector(`input[name="${name}"][value="${value}"]`);
  if (input) input.checked = true;
}

// src/extension/sidepanel/capture-session.js
function createCaptureSession({
  chromeApi,
  portName,
  getCaptureTarget,
  getCaptureOptions,
  onProgress,
  onDone,
  onError,
  onRunningChange
}) {
  let capturePort = null;
  return {
    start() {
      const target = getCaptureTarget();
      if (!target?.bvid) return;
      disconnect();
      onRunningChange(true);
      capturePort = chromeApi.runtime.connect({ name: portName });
      capturePort.onMessage.addListener(handleRuntimeMessage);
      capturePort.onDisconnect.addListener(() => {
        if (capturePort) {
          capturePort = null;
          onRunningChange(false);
        }
      });
      capturePort.postMessage({
        type: "START_CAPTURE",
        payload: {
          url: target.url,
          bvid: target.bvid,
          tabId: target.tabId,
          options: getCaptureOptions()
        }
      });
    },
    cancel() {
      capturePort?.postMessage({ type: "CANCEL_CAPTURE" });
    }
  };
  function handleRuntimeMessage(message) {
    if (message?.type === "PROGRESS") {
      onProgress(message.payload || {});
      return;
    }
    if (message?.type === "DONE") {
      const result = message.payload?.result || null;
      disconnect();
      onRunningChange(false);
      onDone(result);
      return;
    }
    if (message?.type === "ERROR") {
      const error = message.error || {};
      disconnect();
      onRunningChange(false);
      onError(error);
    }
  }
  function disconnect() {
    if (!capturePort) return;
    const port = capturePort;
    capturePort = null;
    port.disconnect();
  }
}

// src/core/exporters.js
var FORMAT_INFO = {
  json: { extension: "json", mimeType: "application/json;charset=utf-8" },
  jsonl: { extension: "jsonl", mimeType: "application/x-ndjson;charset=utf-8" },
  markdown: { extension: "md", mimeType: "text/markdown;charset=utf-8" }
};
var VIDEO_OWNER_MARKER = "\u3010\u7CFB\u7EDF\u6807\u8BB0\uFF1A\u8BE5\u8BC4\u8BBA\u4F5C\u8005\u5DF2\u901A\u8FC7\u7528\u6237 ID \u5339\u914D\u4E3A\u89C6\u9891 UP \u4E3B\u672C\u4EBA\u3011";
function exportCaptureResult(result, format = "json") {
  const info = FORMAT_INFO[format];
  if (!info) {
    throw new Error(`Unsupported export format: ${format}`);
  }
  const generatedAt = result.generatedAt || (/* @__PURE__ */ new Date()).toISOString();
  const filename = makeDownloadFilename({
    bvid: result.video?.bvid || "bilibili",
    title: result.video?.title || "comments",
    generatedAt,
    extension: info.extension
  });
  if (format === "json") {
    return {
      filename,
      mimeType: info.mimeType,
      text: `${JSON.stringify(toAiJson({ ...result, generatedAt }), null, 2)}
`
    };
  }
  if (format === "jsonl") {
    const rows = [
      ...flattenComments(result.pinnedComments, { section: "pinned" }),
      ...flattenComments(result.comments, { section: "normal" })
    ].map((row) => ({
      schemaVersion: result.schemaVersion,
      generatedAt,
      video: result.video,
      ...row
    }));
    return {
      filename,
      mimeType: info.mimeType,
      text: `${rows.map((row) => JSON.stringify(row)).join("\n")}
`
    };
  }
  return {
    filename,
    mimeType: info.mimeType,
    text: toMarkdown({ ...result, generatedAt })
  };
}
function toAiJson(result) {
  const pinnedComments = result.pinnedComments || [];
  const comments = result.comments || [];
  const stats = result.stats || {};
  const videoOwnerMid = normalizeId(result.video?.owner?.mid);
  return {
    format: "bilibili-comment-ai-analysis/v1",
    generatedAt: result.generatedAt,
    schemaVersion: result.schemaVersion || "bili-comment-capture/v1",
    exportGuide: buildExportGuide(result, { includeCounts: true }),
    video: toAiVideo(result.video || {}, result.source || {}),
    captureContext: {
      sourceUrl: result.source?.pageUrl || result.video?.url || "",
      sourceKind: result.source?.kind || "",
      api: result.source?.api || "",
      rootOrder: result.options?.rootOrder || "",
      replyOrder: result.options?.replyOrder || "",
      rootLimit: finiteOrNull(result.options?.rootMaxItems),
      rootPageLimit: finiteOrNull(result.options?.rootMaxPages),
      replyLimitPerRoot: finiteOrNull(result.options?.replyMaxItemsPerRoot),
      replyPageLimitPerRoot: finiteOrNull(result.options?.replyMaxPagesPerRoot),
      includeReplies: Boolean(result.options?.includeReplies),
      reachedRootEnd: Boolean(stats.reachedRootEnd)
    },
    summary: {
      pinnedCommentCount: stats.pinnedComments ?? pinnedComments.length,
      rootCommentCount: stats.rootComments ?? comments.length,
      nestedReplyCount: stats.nestedReplies ?? countReplies([...pinnedComments, ...comments]),
      fetchedRootPages: stats.fetchedRootPages ?? 0,
      fetchedReplyPages: stats.fetchedReplyPages ?? 0
    },
    threads: [
      ...pinnedComments.map((comment, index) => toAiThread(comment, "pinned", index, { videoOwnerMid })),
      ...comments.map(
        (comment, index) => toAiThread(comment, "normal", pinnedComments.length + index, { videoOwnerMid })
      )
    ]
  };
}
function toAiVideo(video, source) {
  const page = video.page || null;
  return {
    bvid: video.bvid || "",
    title: video.title || "",
    url: video.url || source.pageUrl || "",
    ownerName: video.owner?.name || "",
    page: page ? {
      cid: page.cid ?? null,
      page: page.page ?? null,
      part: page.part || "",
      duration: page.duration ?? null
    } : null
  };
}
function toAiThread(comment, threadType, threadIndex, context = {}) {
  const rootComment = toAiComment(comment, "root", {
    rootCommentId: comment.id || null,
    parentCommentId: null,
    videoOwnerMid: context.videoOwnerMid
  });
  return {
    threadType,
    threadIndex,
    rootComment,
    replies: (comment.replies || []).map(
      (reply, replyIndex) => toAiComment(reply, "reply", {
        rootCommentId: reply.rootId || comment.id || null,
        parentCommentId: reply.parentId || comment.id || null,
        replyIndex,
        videoOwnerMid: context.videoOwnerMid
      })
    )
  };
}
function toAiComment(comment, level, context = {}) {
  const isVideoOwner = isCommentByVideoOwner(comment, context.videoOwnerMid);
  return {
    commentId: comment.id || "",
    level,
    authorName: comment.author?.name || "",
    isVideoOwner,
    authorRole: isVideoOwner ? "video_owner" : "viewer",
    authorIdentityLabel: isVideoOwner ? VIDEO_OWNER_MARKER : "",
    text: comment.content?.message || "",
    createdAt: comment.createdAt || null,
    ctime: comment.ctime ?? null,
    likeCount: comment.metrics?.like ?? 0,
    replyCount: comment.metrics?.replyCount ?? 0,
    rootCommentId: context.rootCommentId ?? comment.rootId ?? null,
    parentCommentId: context.parentCommentId ?? comment.parentId ?? null,
    sourceSection: comment.source?.section || "",
    sourcePage: comment.source?.page ?? null,
    indexInPage: comment.source?.indexInPage ?? null,
    replyIndex: context.replyIndex ?? null,
    floor: comment.floor ?? null,
    pictures: comment.content?.pictures || []
  };
}
function toMarkdown(result) {
  const guide = buildExportGuide(result, { includeCounts: true });
  const videoOwnerMid = normalizeId(result.video?.owner?.mid);
  const lines = [
    `# ${result.video?.title || "Bilibili Comments"}`,
    "",
    "## \u5BFC\u51FA\u8BF4\u660E",
    "",
    `- \u89C6\u9891\u6807\u9898\uFF1A${guide.video.title}`,
    `- UP \u4E3B\uFF1A${formatOwnerForMarkdown(guide.video)}`,
    `- BV \u53F7\uFF1A${guide.video.bvid}`,
    `- URL: ${guide.video.url}`,
    `- \u5BFC\u51FA\u65F6\u95F4\uFF1A${result.generatedAt}`,
    `- \u4E3B\u8BC4\u8BBA\u6392\u5E8F\uFF1A${guide.ordering.rootComments}`,
    `- \u697C\u4E2D\u697C\u6392\u5E8F\uFF1A${guide.ordering.nestedReplies}`,
    `- \u8BC4\u8BBA\u7EDF\u8BA1\uFF1A\u7F6E\u9876\u8BC4\u8BBA ${guide.counts.pinnedCommentCount} \u6761\uFF0C\u76F4\u63A5\u8BC4\u8BBA ${guide.counts.directCommentCount} \u6761\uFF0C\u697C\u4E2D\u697C ${guide.counts.nestedReplyCount} \u6761\u3002`,
    "",
    "### \u7ED3\u6784\u89C4\u5219",
    "",
    `- \u76F4\u63A5\u8BC4\u8BBA\uFF1A${guide.terms.directComment}`,
    `- \u697C\u4E2D\u697C\uFF1A${guide.terms.nestedReply}`,
    `- \u7F6E\u9876\u8BC4\u8BBA\uFF1A${guide.terms.pinnedComment}`,
    `- \u8BC4\u8BBA\u4E32\uFF1A${guide.structure.thread}`,
    `- \u8BC4\u8BBA\u987A\u5E8F\u7F16\u53F7\uFF1A${guide.fields.threadIndex}`,
    `- \u697C\u4E2D\u697C\u987A\u5E8F\u7F16\u53F7\uFF1A${guide.fields.replyIndex}`,
    `- \u8BC4\u8BBA ID\uFF1A${guide.fields.commentId}`,
    `- UP \u4E3B\u672C\u4EBA\u6807\u8BB0\uFF1A${guide.fields.isVideoOwner}`,
    `- \u70B9\u8D5E\u6570\uFF1A${guide.fields.likeCount}`,
    `- \u56DE\u590D\u6570\uFF1A${guide.fields.replyCount}`,
    ""
  ];
  if (result.pinnedComments?.length) {
    lines.push("## \u7F6E\u9876\u8BC4\u8BBA", "");
    for (const comment of result.pinnedComments) {
      appendCommentMarkdown(lines, comment, { headingLevel: "###", videoOwnerMid });
    }
  }
  if (result.comments?.length) {
    lines.push("## \u76F4\u63A5\u8BC4\u8BBA", "");
  }
  for (const [index, comment] of (result.comments || []).entries()) {
    appendCommentMarkdown(lines, comment, { prefix: `${index + 1}.`, headingLevel: "###", videoOwnerMid });
  }
  return `${lines.join("\n").trim()}
`;
}
function finiteOrNull(value) {
  return Number.isFinite(value) ? value : null;
}
function countReplies(comments) {
  return comments.reduce((sum, comment) => sum + (comment.replies?.length || 0), 0);
}
function buildExportGuide(result, options = {}) {
  const video = toAiVideo(result.video || {}, result.source || {});
  const pinnedComments = result.pinnedComments || [];
  const comments = result.comments || [];
  const stats = result.stats || {};
  return {
    purpose: "\u8FD9\u4EFD\u6587\u4EF6\u7528\u4E8E\u8BA9 AI \u6216\u4EBA\u5DE5\u9605\u8BFB B \u7AD9\u89C6\u9891\u8BC4\u8BBA\u6293\u53D6\u7ED3\u679C\u3002\u8BF7\u5148\u9605\u8BFB exportGuide\uFF0C\u518D\u5206\u6790 threads \u6216 Markdown \u8BC4\u8BBA\u6B63\u6587\u3002",
    video: {
      title: video.title,
      ownerName: video.ownerName,
      bvid: video.bvid,
      url: video.url,
      page: video.page
    },
    structure: {
      threads: "threads \u662F\u8BC4\u8BBA\u4E32\u6570\u7EC4\uFF0C\u6309\u672C\u6B21\u5BFC\u51FA\u7684\u5C55\u793A\u987A\u5E8F\u6392\u5217\u3002\u6BCF\u4E2A thread \u90FD\u7531\u4E00\u6761\u76F4\u63A5\u8BC4\u8BBA rootComment \u548C\u5B83\u4E0B\u9762\u7684 replies \u7EC4\u6210\u3002",
      thread: "\u4E00\u6761\u8BC4\u8BBA\u4E32\u4EE3\u8868\u4E00\u4E2A\u89C6\u9891\u7B2C\u4E00\u5C42\u8BC4\u8BBA\u53CA\u5176\u4E0B\u65B9\u697C\u4E2D\u697C\u56DE\u590D\uFF1B\u7F6E\u9876\u8BC4\u8BBA\u4E5F\u6309\u540C\u6837\u7ED3\u6784\u8868\u8FBE\u3002",
      rootComment: "rootComment \u662F\u76F4\u63A5\u8BC4\u8BBA\uFF0C\u5373\u89C6\u9891\u8BC4\u8BBA\u533A\u7B2C\u4E00\u5C42\u8BC4\u8BBA\u3002",
      replies: "replies \u662F\u697C\u4E2D\u697C\uFF0C\u5373\u76F4\u63A5\u8BC4\u8BBA\u4E0B\u9762\u7684\u7B2C\u4E8C\u5C42\u56DE\u590D\u6570\u7EC4\u3002"
    },
    terms: {
      directComment: "\u89C6\u9891\u8BC4\u8BBA\u533A\u7B2C\u4E00\u5C42\u8BC4\u8BBA\uFF1B\u5728 JSON \u4E2D\u5BF9\u5E94 rootComment\uFF0C\u5728 Markdown \u4E2D\u5BF9\u5E94\u201C\u76F4\u63A5\u8BC4\u8BBA\u201D\u3002",
      nestedReply: "\u76F4\u63A5\u8BC4\u8BBA\u4E0B\u9762\u7684\u56DE\u590D\uFF1B\u4E5F\u5C31\u662F\u901A\u5E38\u8BF4\u7684\u697C\u4E2D\u697C\u3002\u5728 JSON \u4E2D\u5BF9\u5E94 replies \u6570\u7EC4\u91CC\u7684\u6BCF\u4E00\u9879\uFF0C\u5728 Markdown \u4E2D\u5BF9\u5E94\u76F4\u63A5\u8BC4\u8BBA\u4E0B\u65B9\u7684\u201C\u697C\u4E2D\u697C\u201D\u3002",
      pinnedComment: "B \u7AD9\u7F6E\u9876\u8BC4\u8BBA\uFF1B\u5B83\u4E5F\u662F\u7B2C\u4E00\u5C42\u76F4\u63A5\u8BC4\u8BBA\uFF0C\u4F46 threadType \u4E3A pinned\uFF0C\u7EDF\u8BA1\u65F6\u5355\u72EC\u5217\u51FA\u3002"
    },
    fields: {
      threadIndex: "\u4ECE 0 \u5F00\u59CB\uFF0C\u8868\u793A\u8BE5\u8BC4\u8BBA\u4E32\u5728\u672C\u5BFC\u51FA threads \u6570\u7EC4\u4E2D\u7684\u4F4D\u7F6E\uFF0C\u4E0D\u662F B \u7AD9\u697C\u5C42\u53F7\u3002",
      replyIndex: "\u4ECE 0 \u5F00\u59CB\uFF0C\u8868\u793A\u8BE5\u56DE\u590D\u5728\u6240\u5C5E\u76F4\u63A5\u8BC4\u8BBA replies \u6570\u7EC4\u4E2D\u7684\u4F4D\u7F6E\u3002",
      commentId: "B \u7AD9\u8BC4\u8BBA RPID\uFF0C\u53EF\u7528\u4E8E\u552F\u4E00\u8BC6\u522B\u4E00\u6761\u8BC4\u8BBA\u6216\u56DE\u590D\u3002",
      authorName: "\u8BC4\u8BBA\u4EBA\u7684\u516C\u5F00\u6635\u79F0\u3002",
      isVideoOwner: `\u5982\u679C\u8BC4\u8BBA\u4F5C\u8005\u7684\u7528\u6237 ID \u4E0E\u89C6\u9891 UP \u4E3B\u7528\u6237 ID \u5B8C\u5168\u4E00\u81F4\uFF0C\u5219\u8FFD\u52A0 ${VIDEO_OWNER_MARKER}\uFF1B\u53EA\u770B\u7528\u6237 ID\uFF0C\u4E0D\u6309\u6635\u79F0\u5224\u65AD\uFF0C\u6240\u4EE5\u540C\u540D\u9AD8\u4EFF\u4E0D\u4F1A\u88AB\u6807\u8BB0\u3002`,
      text: "\u8BC4\u8BBA\u6216\u56DE\u590D\u7684\u6B63\u6587\u5185\u5BB9\u3002",
      likeCount: "\u6307\u5F53\u524D\u8FD9\u4E00\u6761\u8BC4\u8BBA\u6216\u56DE\u590D\u672C\u8EAB\u6536\u5230\u7684\u70B9\u8D5E\u6570\u3002",
      replyCount: "\u6307\u5F53\u524D\u76F4\u63A5\u8BC4\u8BBA\u4E0B\u9762\u7684\u697C\u4E2D\u697C\u56DE\u590D\u603B\u6570\uFF1B\u697C\u4E2D\u697C\u81EA\u8EAB\u901A\u5E38\u6CA1\u6709\u4E0B\u7EA7\u56DE\u590D\u3002",
      rootCommentId: "\u6240\u5C5E\u76F4\u63A5\u8BC4\u8BBA\u7684\u8BC4\u8BBA ID\uFF1B\u76F4\u63A5\u8BC4\u8BBA\u81EA\u8EAB\u7B49\u4E8E\u81EA\u5DF1\u7684 commentId\u3002",
      parentCommentId: "\u7236\u8BC4\u8BBA ID\uFF1B\u697C\u4E2D\u697C\u901A\u5E38\u6307\u5411\u6240\u5C5E\u76F4\u63A5\u8BC4\u8BBA\u6216\u88AB\u56DE\u590D\u7684\u697C\u4E2D\u697C\u3002",
      sourcePage: "\u672C\u5DE5\u5177\u6293\u53D6\u8BE5\u8BC4\u8BBA\u65F6\u6240\u5728\u7684\u63A5\u53E3\u5206\u9875\u9875\u7801\u3002",
      indexInPage: "\u8BE5\u8BC4\u8BBA\u5728\u6293\u53D6\u5230\u7684\u63A5\u53E3\u5206\u9875\u5185\u7684\u539F\u59CB\u5E8F\u53F7\uFF0C\u4ECE 0 \u5F00\u59CB\u3002",
      floor: "B \u7AD9\u8FD4\u56DE\u7684\u697C\u5C42\u5B57\u6BB5\uFF1B\u53EF\u80FD\u4E3A\u7A7A\u6216\u4E0D\u8FDE\u7EED\uFF0C\u4E0D\u5E94\u5F53\u66FF\u4EE3 threadIndex \u4F5C\u4E3A\u672C\u5BFC\u51FA\u987A\u5E8F\u3002"
    },
    ordering: {
      rootComments: describeOrder(result.options?.rootOrder, "root"),
      nestedReplies: describeOrder(result.options?.replyOrder, "reply")
    },
    counts: options.includeCounts ? {
      pinnedCommentCount: stats.pinnedComments ?? pinnedComments.length,
      directCommentCount: stats.rootComments ?? comments.length,
      nestedReplyCount: stats.nestedReplies ?? countReplies([...pinnedComments, ...comments])
    } : void 0
  };
}
function describeOrder(order, level) {
  if (order === "latest") {
    return level === "root" ? "\u6700\u65B0\u8BC4\u8BBA\u987A\u5E8F\uFF0C\u6309\u53D1\u5E03\u65F6\u95F4\u4ECE\u65B0\u5230\u65E7\u6392\u5217\u76F4\u63A5\u8BC4\u8BBA\u3002" : "\u65F6\u95F4\u5012\u5E8F\uFF0C\u6309\u672C\u6B21\u6293\u53D6\u5230\u7684\u697C\u4E2D\u697C\u53D1\u5E03\u65F6\u95F4\u4ECE\u65B0\u5230\u65E7\u6392\u5217\uFF1B\u8FD9\u4E0D\u662F B \u7AD9\u5168\u91CF\u697C\u4E2D\u697C\u6700\u65B0\u8BC4\u8BBA\u6D41\u3002";
  }
  return level === "root" ? "B \u7AD9\u9ED8\u8BA4\u987A\u5E8F\uFF0C\u672C\u5DE5\u5177\u6309\u63A5\u53E3\u8FD4\u56DE\u7684\u9ED8\u8BA4/\u7EFC\u5408\u70ED\u5EA6\u5C55\u793A\u987A\u5E8F\u4FDD\u7559\u76F4\u63A5\u8BC4\u8BBA\uFF0C\u4E0D\u989D\u5916\u6309\u70B9\u8D5E\u6570\u6216\u65F6\u95F4\u91CD\u6392\u3002" : "B \u7AD9\u9ED8\u8BA4\u987A\u5E8F\uFF0C\u672C\u5DE5\u5177\u5148\u4FDD\u7559\u9875\u9762\u5F53\u524D\u53EF\u89C1\u9884\u89C8\u91CC\u7684\u697C\u4E2D\u697C\u987A\u5E8F\uFF0C\u518D\u7528\u5C55\u5F00\u5217\u8868\u63A5\u53E3\u8865\u8DB3\u540E\u7EED\u56DE\u590D\u5E76\u53BB\u91CD\uFF0C\u4E0D\u989D\u5916\u6309\u70B9\u8D5E\u6570\u6216\u65F6\u95F4\u91CD\u6392\u3002";
}
function formatOwnerForMarkdown(video) {
  return video.ownerName || "\u672A\u77E5";
}
function appendCommentMarkdown(lines, comment, options = {}) {
  const headingLevel = options.headingLevel || "##";
  const prefix = options.prefix ? `${options.prefix} ` : "";
  const label = options.prefix ? "\u76F4\u63A5\u8BC4\u8BBA" : "\u7F6E\u9876\u8BC4\u8BBA";
  lines.push(`${headingLevel} ${prefix}${label} \xB7 ${formatCommentAuthor(comment, options.videoOwnerMid)}`);
  if (comment.id) lines.push(`- \u8BC4\u8BBA ID\uFF1A${comment.id}`);
  if (comment.createdAt) lines.push(`- \u53D1\u5E03\u65F6\u95F4\uFF1A${comment.createdAt}`);
  lines.push(`- \u70B9\u8D5E\u6570\uFF1A${comment.metrics?.like ?? 0}`);
  lines.push(`- \u56DE\u590D\u6570\uFF1A${comment.metrics?.replyCount ?? comment.replies?.length ?? 0}`);
  lines.push("");
  lines.push("\u5185\u5BB9\uFF1A");
  lines.push("");
  lines.push(comment.content?.message || "");
  lines.push("");
  if (comment.replies?.length) {
    lines.push("#### \u697C\u4E2D\u697C", "");
  }
  for (const [replyIndex, reply] of (comment.replies || []).entries()) {
    lines.push(`- \u697C\u4E2D\u697C #${replyIndex + 1} \xB7 ${formatCommentAuthor(reply, options.videoOwnerMid)}`);
    if (reply.id) lines.push(`  - \u8BC4\u8BBA ID\uFF1A${reply.id}`);
    if (reply.rootId || comment.id) lines.push(`  - \u6240\u5C5E\u76F4\u63A5\u8BC4\u8BBA ID\uFF1A${reply.rootId || comment.id}`);
    if (reply.parentId) lines.push(`  - \u7236\u8BC4\u8BBA ID\uFF1A${reply.parentId}`);
    if (reply.createdAt) lines.push(`  - \u53D1\u5E03\u65F6\u95F4\uFF1A${reply.createdAt}`);
    lines.push(`  - \u70B9\u8D5E\u6570\uFF1A${reply.metrics?.like ?? 0}`);
    lines.push("  - \u5185\u5BB9\uFF1A");
    for (const line of String(reply.content?.message || "").split("\n")) {
      lines.push(`    ${line}`);
    }
    lines.push("");
  }
}
function formatCommentAuthor(comment, videoOwnerMid) {
  const name = comment.author?.name || "Unknown";
  return isCommentByVideoOwner(comment, videoOwnerMid) ? `${name}${VIDEO_OWNER_MARKER}` : name;
}
function isCommentByVideoOwner(comment, videoOwnerMid) {
  const ownerMid = normalizeId(videoOwnerMid);
  return Boolean(ownerMid && normalizeId(comment.author?.mid) === ownerMid);
}
function normalizeId(value) {
  if (value === void 0 || value === null || value === "") return "";
  return String(value);
}

// src/extension/sidepanel/comments-view.js
function renderEmptyComments(elements2) {
  elements2.resultTitle.textContent = t("results.emptyTitle");
  elements2.resultMeta.textContent = t("results.emptyMeta");
  elements2.resultStats.textContent = t("results.notCaptured");
  elements2.commentList.textContent = "";
  elements2.commentList.append(emptyMessage(t("results.emptyList")));
  elements2.commentSearch.value = "";
  elements2.commentSearch.disabled = true;
  elements2.copyAllComments.disabled = true;
  elements2.exportJson.disabled = true;
  elements2.exportMarkdown.disabled = true;
}
function renderCapturedComments(elements2, result) {
  elements2.commentList.textContent = "";
  elements2.resultTitle.textContent = result?.video?.title || t("results.untitledVideo");
  elements2.resultMeta.textContent = `${result?.video?.bvid || ""} \xB7 ${result?.source?.pageUrl || ""}`.trim();
  const allThreads = toThreads(result);
  const searchQuery = elements2.commentSearch.value || "";
  const threads = filterCommentThreads(allThreads, searchQuery);
  const stats = result?.stats || {};
  const pinned = stats.pinnedComments ? t("results.statsPinned", { count: formatNumber(stats.pinnedComments) }) : "";
  elements2.resultStats.textContent = t("results.stats", {
    pinned,
    roots: formatNumber(stats.rootComments),
    replies: formatNumber(stats.nestedReplies)
  });
  elements2.commentSearch.disabled = allThreads.length === 0;
  elements2.copyAllComments.disabled = allThreads.length === 0;
  elements2.exportJson.disabled = allThreads.length === 0;
  elements2.exportMarkdown.disabled = allThreads.length === 0;
  if (!allThreads.length) {
    elements2.commentList.append(emptyMessage(t("empty.noComments")));
    return;
  }
  if (!threads.length) {
    elements2.commentList.append(emptyMessage(t("empty.noMatches", { query: searchQuery.trim() })));
    return;
  }
  for (const thread of threads) {
    elements2.commentList.append(renderCommentThread(thread));
  }
}
function filterCommentThreads(threads, query) {
  const normalizedQuery = normalizeSearchText(query);
  if (!normalizedQuery) return threads;
  return (threads || []).filter((thread) => threadMatchesSearch(thread, normalizedQuery));
}
async function copyAllComments(elements2, result) {
  if (!result) return;
  const threads = toThreads(result);
  if (!threads.length) return;
  const text = formatCopyText(result);
  try {
    await navigator.clipboard.writeText(text);
  } catch (_error) {
    const textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.append(textarea);
    textarea.select();
    document.execCommand("copy");
    textarea.remove();
  }
  setCommentsFeedback(elements2, t("copy.done"));
}
function exportCommentsAsJson(elements2, result) {
  exportComments(elements2, result, "json", t("status.exportedJson"));
}
function exportCommentsAsMarkdown(elements2, result) {
  exportComments(elements2, result, "markdown", t("status.exportedMarkdown"));
}
function exportComments(elements2, result, format, feedback) {
  if (!result) return;
  const exported = exportCaptureResult(result, format);
  const blob = new Blob([exported.text], { type: exported.mimeType });
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = objectUrl;
  anchor.download = exported.filename;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(objectUrl), 1e3);
  setCommentsFeedback(elements2, feedback);
}
function setCommentsFeedback(elements2, message) {
  elements2.commentsFeedback.textContent = message;
}
function renderCommentThread({ comment, label }) {
  const item = document.createElement("article");
  item.className = "comment-thread";
  const head = document.createElement("div");
  head.className = "comment-line-head";
  const author = document.createElement("span");
  author.className = "comment-author";
  author.textContent = `${label} \xB7 ${comment.author?.name || "Unknown"}`;
  const metrics = document.createElement("span");
  metrics.textContent = t("comment.metrics", {
    time: formatTime(comment.ctime),
    likes: formatNumber(comment.metrics?.like || 0),
    replies: formatNumber(comment.metrics?.replyCount || 0)
  });
  head.append(author, metrics);
  const text = document.createElement("div");
  text.className = "comment-text";
  text.textContent = comment.content?.message || "";
  item.append(head, text);
  if (comment.replies?.length) {
    const replies = document.createElement("div");
    replies.className = "comment-replies";
    for (const reply of comment.replies) {
      replies.append(renderReplyLine(reply));
    }
    item.append(replies);
  }
  return item;
}
function renderReplyLine(reply) {
  const line = document.createElement("div");
  line.className = "comment-reply";
  const name = document.createElement("strong");
  name.textContent = reply.author?.name || "Unknown";
  line.append(name, document.createTextNode(`\uFF1A${reply.content?.message || ""}`));
  return line;
}
function threadMatchesSearch(thread, query) {
  const comment = thread?.comment || {};
  return textMatches(thread?.label, query) || textMatches(comment.author?.name, query) || textMatches(comment.content?.message, query) || textMatches(comment.id, query) || (comment.replies || []).some(
    (reply) => textMatches(reply.author?.name, query) || textMatches(reply.content?.message, query) || textMatches(reply.id, query)
  );
}
function textMatches(value, query) {
  return normalizeSearchText(value).includes(query);
}
function formatCopyText(result) {
  return exportCaptureResult(result, "markdown").text;
}
function toThreads(result) {
  return [
    ...(result?.pinnedComments || []).map((comment) => ({ comment, label: t("thread.pinned") })),
    ...(result?.comments || []).map((comment, index) => ({ comment, label: `#${index + 1}` }))
  ];
}
function emptyMessage(text) {
  const empty = document.createElement("p");
  empty.className = "empty-state";
  empty.textContent = text;
  return empty;
}
function normalizeSearchText(value) {
  return String(value || "").trim().toLowerCase();
}
function formatNumber(value) {
  return new Intl.NumberFormat("zh-CN").format(Number(value) || 0);
}
function formatTime(ctime) {
  if (!ctime) return "";
  const date = new Date(Number(ctime) * 1e3);
  return `${date.getMonth() + 1}-${date.getDate()} ${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
}

// src/extension/sidepanel/elements.js
function getSidePanelElements() {
  return {
    viewButtons: [...document.querySelectorAll("[data-view-target]")],
    viewPanels: [...document.querySelectorAll("[data-view-panel]")],
    localeButtons: [...document.querySelectorAll("[data-locale-option]")],
    activeVideoCard: byId("active-video-card"),
    activeVideoTitle: byId("active-video-title"),
    activeVideoMeta: byId("active-video-meta"),
    refreshActiveVideo: byId("refresh-active-video"),
    openAiAnalysis: byId("open-ai-analysis"),
    captureSummary: byId("capture-summary"),
    captureOptionControls: [...document.querySelectorAll("#view-capture input")],
    rootLoads: byId("root-loads"),
    rootLoadsAll: byId("root-loads-all"),
    rootItems: byId("root-items"),
    rootItemsAll: byId("root-items-all"),
    includeReplies: byId("include-replies"),
    replyOptionsPanel: document.querySelector(".reply-comment-options"),
    replyOptionControls: [...document.querySelectorAll(".reply-comment-options input:not(#include-replies)")],
    replyLoads: byId("reply-loads"),
    replyLoadsAll: byId("reply-loads-all"),
    replyItems: byId("reply-items"),
    replyItemsAll: byId("reply-items-all"),
    startCapture: byId("start-capture"),
    cancelCapture: byId("cancel-capture"),
    progressTrack: document.querySelector(".progress-track"),
    progressBar: byId("progress-bar"),
    progressText: byId("progress-text"),
    errorText: byId("error-text"),
    resultTitle: byId("result-title"),
    resultMeta: byId("result-meta"),
    resultStats: byId("result-stats"),
    commentList: byId("comment-list"),
    commentSearch: byId("comment-search"),
    commentsFeedback: byId("comments-feedback"),
    copyAllComments: byId("copy-all-comments"),
    exportJson: byId("export-json"),
    exportMarkdown: byId("export-markdown")
  };
}
function byId(id) {
  return document.getElementById(id);
}

// src/extension/sidepanel/progress-view.js
function renderCaptureProgress(elements2, progress, options) {
  if (progress.phase === "start") {
    setCaptureProgress(elements2, 8, t("progress.start"));
    return;
  }
  if (progress.phase === "video") {
    setCaptureProgress(elements2, 12, t("progress.readVideo"));
    return;
  }
  if (progress.phase === "root") {
    const max = isAllLimit(options.rootMaxPages) ? Math.max(progress.page || 1, 20) : options.rootMaxPages;
    const percent = Math.min(72, 12 + (progress.page || 1) / max * 42);
    setCaptureProgress(elements2, percent, t("progress.root", { page: progress.page || 1, count: progress.fetched || 0 }));
    return;
  }
  if (progress.phase === "reply") {
    const percent = 58 + (progress.rootIndex || 1) / Math.max(1, progress.rootTotal || 1) * 34;
    setCaptureProgress(elements2, percent, t("progress.replies", { current: progress.rootIndex || 1, total: progress.rootTotal || 1 }));
    return;
  }
  setCaptureProgress(elements2, 8, progress.message || t("progress.running"));
}
function isAllLimit(value) {
  return value === "all" || value === Infinity;
}
function setCaptureProgress(elements2, percent, text) {
  const value = Math.max(0, Math.min(100, Math.round(percent)));
  elements2.progressBar.style.width = `${value}%`;
  elements2.progressTrack.setAttribute("aria-valuenow", String(value));
  elements2.progressText.textContent = text;
}
function renderCaptureError(elements2, message) {
  elements2.errorText.hidden = false;
  elements2.errorText.textContent = message;
}
function clearCaptureError(elements2) {
  elements2.errorText.hidden = true;
  elements2.errorText.textContent = "";
}

// src/extension/sidepanel/view-router.js
function activateView(name) {
  for (const button of document.querySelectorAll("[data-view-target]")) {
    button.classList.toggle("is-active", button.dataset.viewTarget === name);
  }
  for (const panel of document.querySelectorAll("[data-view-panel]")) {
    const active = panel.dataset.viewPanel === name;
    panel.hidden = !active;
    panel.classList.toggle("is-active", active);
  }
}
function setViewEnabled(name, enabled) {
  const button = document.querySelector(`[data-view-target="${name}"]`);
  if (button) button.disabled = !enabled;
}

// src/extension/sidepanel-entry.js
var PORT_NAME = "bili-comment-capture";
var elements = getSidePanelElements();
var sidePanelState = {
  activeVideo: null,
  latestCaptureResult: null,
  isCaptureRunning: false,
  runningCaptureOptions: null,
  progressStatus: "waiting",
  latestProgress: null
};
var captureSession = createCaptureSession({
  chromeApi: chrome,
  portName: PORT_NAME,
  getCaptureTarget: () => sidePanelState.activeVideo,
  getCaptureOptions: () => readCaptureOptionsFromForm(elements),
  onProgress: handleCaptureProgress,
  onDone: handleCaptureDone,
  onError: handleCaptureError,
  onRunningChange: setCaptureRunning
});
init();
async function init() {
  await loadUiLocale(chrome.storage.local);
  applyLocale(elements);
  bindViewSwitching();
  bindCaptureOptionEvents(elements, handleCaptureOptionChange);
  bindActions();
  await loadCaptureOptions(chrome.storage.local, elements);
  syncCaptureLimitInputs(elements);
  updateCaptureSummary(elements);
  renderEmptyComments(elements);
  watchActiveVideoTabs(chrome, detectActiveVideo);
  await detectActiveVideo();
}
function bindViewSwitching() {
  for (const button of elements.viewButtons) {
    button.addEventListener("click", () => activateView(button.dataset.viewTarget));
  }
}
function bindActions() {
  for (const button of elements.localeButtons) {
    button.addEventListener("click", () => changeLocale(button.dataset.localeOption));
  }
  elements.refreshActiveVideo.addEventListener("click", detectActiveVideo);
  elements.openAiAnalysis.addEventListener("click", openAiAnalysis);
  elements.startCapture.addEventListener("click", startCapture);
  elements.cancelCapture.addEventListener("click", () => captureSession.cancel());
  elements.copyAllComments.addEventListener(
    "click",
    () => copyAllComments(elements, sidePanelState.latestCaptureResult)
  );
  elements.exportJson.addEventListener(
    "click",
    () => exportCommentsAsJson(elements, sidePanelState.latestCaptureResult)
  );
  elements.exportMarkdown.addEventListener(
    "click",
    () => exportCommentsAsMarkdown(elements, sidePanelState.latestCaptureResult)
  );
  elements.commentSearch.addEventListener(
    "input",
    () => renderCapturedComments(elements, sidePanelState.latestCaptureResult)
  );
}
async function changeLocale(locale) {
  await saveUiLocale(chrome.storage.local, locale);
  applyLocale(elements);
  refreshProgressForLocale();
  updateCaptureSummary(elements);
  if (sidePanelState.latestCaptureResult) {
    renderCapturedComments(elements, sidePanelState.latestCaptureResult);
  } else {
    renderEmptyComments(elements);
  }
  await detectActiveVideo();
}
function handleCaptureOptionChange() {
  syncCaptureLimitInputs(elements);
  updateCaptureSummary(elements);
  void saveCaptureOptions(chrome.storage.local, elements);
}
async function detectActiveVideo() {
  await detectActiveVideoTab(chrome, {
    onLoading() {
      setActiveVideo(null);
      renderActiveVideoState("loading", t("active.loadingTitle"), t("active.loadingMeta"));
      refreshCaptureControls();
    },
    onReady(video) {
      setActiveVideo(video);
      renderActiveVideoState("ready", video.title, `${video.bvid} \xB7 ${t("active.currentVideoPage")}`);
      refreshCaptureControls();
    },
    onMissing(title) {
      setActiveVideo(null);
      renderActiveVideoState("missing", t("active.missingTitle"), title || t("active.missingMeta"));
      refreshCaptureControls();
    }
  });
}
function setActiveVideo(video) {
  sidePanelState.activeVideo = video;
}
function renderActiveVideoState(kind, title, meta) {
  elements.activeVideoCard.classList.toggle("is-ready", kind === "ready");
  elements.activeVideoCard.classList.toggle("is-missing", kind === "missing");
  elements.activeVideoTitle.textContent = title;
  elements.activeVideoMeta.textContent = meta;
}
function startCapture() {
  if (!sidePanelState.activeVideo?.bvid) {
    renderCaptureError(elements, t("error.needVideo"));
    activateView("capture");
    return;
  }
  sidePanelState.latestCaptureResult = null;
  sidePanelState.runningCaptureOptions = readCaptureOptionsFromForm(elements);
  sidePanelState.latestProgress = null;
  sidePanelState.progressStatus = "running";
  setViewEnabled("comments", false);
  renderEmptyComments(elements);
  setCommentsFeedback(elements, "");
  clearCaptureError(elements);
  activateView("capture");
  setCaptureProgress(elements, 6, t("progress.start"));
  captureSession.start();
}
async function openAiAnalysis() {
  const target = selectAiAnalysisTarget({
    activeVideo: sidePanelState.activeVideo,
    latestCaptureResult: sidePanelState.latestCaptureResult
  });
  if (!target?.bvid) {
    renderCaptureError(elements, t("error.needVideo"));
    return;
  }
  try {
    const url = buildSiteResultUrl({
      bvid: target.bvid,
      url: target.url,
      video: target.video
    });
    await chrome.tabs.create({ url });
  } catch (error) {
    renderCaptureError(elements, error?.message || t("error.openAnalysis"));
  }
}
function handleCaptureProgress(progress) {
  sidePanelState.progressStatus = "running";
  sidePanelState.latestProgress = progress;
  renderCaptureProgress(elements, progress, sidePanelState.runningCaptureOptions || readCaptureOptionsFromForm(elements));
}
function handleCaptureDone(result) {
  sidePanelState.latestCaptureResult = result;
  sidePanelState.progressStatus = "done";
  sidePanelState.latestProgress = null;
  sidePanelState.runningCaptureOptions = null;
  setCaptureProgress(elements, 100, t("progress.done"));
  renderCapturedComments(elements, result);
  setViewEnabled("comments", true);
  activateView("comments");
}
function handleCaptureError(error) {
  const isAbort = error?.name === "AbortError";
  sidePanelState.progressStatus = isAbort ? "stopped" : "failed";
  sidePanelState.latestProgress = null;
  sidePanelState.runningCaptureOptions = null;
  setCaptureProgress(elements, 100, isAbort ? t("progress.stopped") : t("progress.failed"));
  if (!isAbort) renderCaptureError(elements, error?.message || t("error.captureFailed"));
  activateView("capture");
}
function setCaptureRunning(isRunning) {
  sidePanelState.isCaptureRunning = isRunning;
  elements.cancelCapture.disabled = !isRunning;
  setCaptureOptionsLocked(elements, isRunning);
  refreshCaptureControls();
}
function refreshCaptureControls() {
  elements.startCapture.disabled = sidePanelState.isCaptureRunning || !sidePanelState.activeVideo?.bvid;
  elements.openAiAnalysis.disabled = !sidePanelState.activeVideo?.bvid && !sidePanelState.latestCaptureResult?.video?.bvid;
}
function refreshProgressForLocale() {
  if (sidePanelState.progressStatus === "running" && sidePanelState.latestProgress) {
    renderCaptureProgress(elements, sidePanelState.latestProgress, sidePanelState.runningCaptureOptions || readCaptureOptionsFromForm(elements));
    return;
  }
  const progressKeys = {
    done: "progress.done",
    failed: "progress.failed",
    stopped: "progress.stopped",
    waiting: "progress.waiting"
  };
  const key = progressKeys[sidePanelState.progressStatus] || "progress.waiting";
  const value = sidePanelState.progressStatus === "waiting" ? 0 : 100;
  setCaptureProgress(elements, value, t(key));
}
