// Generated by scripts/build.mjs from src/extension/content-entry.js. Do not edit this file directly.
(() => {
  // src/core/video.js
  var BVID_RE = /(BV[0-9A-Za-z]{10,})/;
  function extractBvid(input) {
    if (!input) return "";
    const match = String(input).match(BVID_RE);
    return match ? match[1] : "";
  }

  // src/extension/content-entry.js
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type !== "GET_BILI_PAGE_CONTEXT") return false;
    const canonical = document.querySelector('link[rel="canonical"]')?.href || "";
    const ogTitle = document.querySelector('meta[property="og:title"]')?.content || "";
    const url = canonical || location.href;
    sendResponse({
      ok: true,
      url,
      title: ogTitle || document.title || "",
      bvid: extractBvid(url || location.href)
    });
    return false;
  });
})();
