// Generated by scripts/build.mjs from src/extension/background-entry.js. Do not edit this file directly.
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// (disabled):crypto
var require_crypto = __commonJS({
  "(disabled):crypto"() {
  }
});

// (disabled):buffer
var require_buffer = __commonJS({
  "(disabled):buffer"() {
  }
});

// node_modules/js-md5/src/md5.js
var require_md5 = __commonJS({
  "node_modules/js-md5/src/md5.js"(exports, module) {
    (function() {
      "use strict";
      var INPUT_ERROR = "input is invalid type";
      var FINALIZE_ERROR = "finalize already called";
      var WINDOW = typeof window === "object";
      var root = WINDOW ? window : {};
      if (root.JS_MD5_NO_WINDOW) {
        WINDOW = false;
      }
      var WEB_WORKER = !WINDOW && typeof self === "object";
      var NODE_JS = !root.JS_MD5_NO_NODE_JS && typeof process === "object" && process.versions && process.versions.node;
      if (NODE_JS) {
        root = global;
      } else if (WEB_WORKER) {
        root = self;
      }
      var COMMON_JS = !root.JS_MD5_NO_COMMON_JS && typeof module === "object" && module.exports;
      var AMD = typeof define === "function" && define.amd;
      var ARRAY_BUFFER = !root.JS_MD5_NO_ARRAY_BUFFER && typeof ArrayBuffer !== "undefined";
      var HEX_CHARS = "0123456789abcdef".split("");
      var EXTRA = [128, 32768, 8388608, -2147483648];
      var SHIFT = [0, 8, 16, 24];
      var OUTPUT_TYPES = ["hex", "array", "digest", "buffer", "arrayBuffer", "base64"];
      var BASE64_ENCODE_CHAR = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split("");
      var blocks = [], buffer8;
      if (ARRAY_BUFFER) {
        var buffer = new ArrayBuffer(68);
        buffer8 = new Uint8Array(buffer);
        blocks = new Uint32Array(buffer);
      }
      var isArray = Array.isArray;
      if (root.JS_MD5_NO_NODE_JS || !isArray) {
        isArray = function(obj) {
          return Object.prototype.toString.call(obj) === "[object Array]";
        };
      }
      var isView = ArrayBuffer.isView;
      if (ARRAY_BUFFER && (root.JS_MD5_NO_ARRAY_BUFFER_IS_VIEW || !isView)) {
        isView = function(obj) {
          return typeof obj === "object" && obj.buffer && obj.buffer.constructor === ArrayBuffer;
        };
      }
      var formatMessage = function(message) {
        var type = typeof message;
        if (type === "string") {
          return [message, true];
        }
        if (type !== "object" || message === null) {
          throw new Error(INPUT_ERROR);
        }
        if (ARRAY_BUFFER && message.constructor === ArrayBuffer) {
          return [new Uint8Array(message), false];
        }
        if (!isArray(message) && !isView(message)) {
          throw new Error(INPUT_ERROR);
        }
        return [message, false];
      };
      var createOutputMethod = function(outputType) {
        return function(message) {
          return new Md5(true).update(message)[outputType]();
        };
      };
      var createMethod = function() {
        var method = createOutputMethod("hex");
        if (NODE_JS) {
          method = nodeWrap(method);
        }
        method.create = function() {
          return new Md5();
        };
        method.update = function(message) {
          return method.create().update(message);
        };
        for (var i = 0; i < OUTPUT_TYPES.length; ++i) {
          var type = OUTPUT_TYPES[i];
          method[type] = createOutputMethod(type);
        }
        return method;
      };
      var nodeWrap = function(method) {
        var crypto = require_crypto();
        var Buffer2 = require_buffer().Buffer;
        var bufferFrom;
        if (Buffer2.from && !root.JS_MD5_NO_BUFFER_FROM) {
          bufferFrom = Buffer2.from;
        } else {
          bufferFrom = function(message) {
            return new Buffer2(message);
          };
        }
        var nodeMethod = function(message) {
          if (typeof message === "string") {
            return crypto.createHash("md5").update(message, "utf8").digest("hex");
          } else {
            if (message === null || message === void 0) {
              throw new Error(INPUT_ERROR);
            } else if (message.constructor === ArrayBuffer) {
              message = new Uint8Array(message);
            }
          }
          if (isArray(message) || isView(message) || message.constructor === Buffer2) {
            return crypto.createHash("md5").update(bufferFrom(message)).digest("hex");
          } else {
            return method(message);
          }
        };
        return nodeMethod;
      };
      var createHmacOutputMethod = function(outputType) {
        return function(key, message) {
          return new HmacMd5(key, true).update(message)[outputType]();
        };
      };
      var createHmacMethod = function() {
        var method = createHmacOutputMethod("hex");
        method.create = function(key) {
          return new HmacMd5(key);
        };
        method.update = function(key, message) {
          return method.create(key).update(message);
        };
        for (var i = 0; i < OUTPUT_TYPES.length; ++i) {
          var type = OUTPUT_TYPES[i];
          method[type] = createHmacOutputMethod(type);
        }
        return method;
      };
      function Md5(sharedMemory) {
        if (sharedMemory) {
          blocks[0] = blocks[16] = blocks[1] = blocks[2] = blocks[3] = blocks[4] = blocks[5] = blocks[6] = blocks[7] = blocks[8] = blocks[9] = blocks[10] = blocks[11] = blocks[12] = blocks[13] = blocks[14] = blocks[15] = 0;
          this.blocks = blocks;
          this.buffer8 = buffer8;
        } else {
          if (ARRAY_BUFFER) {
            var buffer2 = new ArrayBuffer(68);
            this.buffer8 = new Uint8Array(buffer2);
            this.blocks = new Uint32Array(buffer2);
          } else {
            this.blocks = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
          }
        }
        this.h0 = this.h1 = this.h2 = this.h3 = this.start = this.bytes = this.hBytes = 0;
        this.finalized = this.hashed = false;
        this.first = true;
      }
      Md5.prototype.update = function(message) {
        if (this.finalized) {
          throw new Error(FINALIZE_ERROR);
        }
        var result = formatMessage(message);
        message = result[0];
        var isString = result[1];
        var code, index = 0, i, length = message.length, blocks2 = this.blocks;
        var buffer82 = this.buffer8;
        while (index < length) {
          if (this.hashed) {
            this.hashed = false;
            blocks2[0] = blocks2[16];
            blocks2[16] = blocks2[1] = blocks2[2] = blocks2[3] = blocks2[4] = blocks2[5] = blocks2[6] = blocks2[7] = blocks2[8] = blocks2[9] = blocks2[10] = blocks2[11] = blocks2[12] = blocks2[13] = blocks2[14] = blocks2[15] = 0;
          }
          if (isString) {
            if (ARRAY_BUFFER) {
              for (i = this.start; index < length && i < 64; ++index) {
                code = message.charCodeAt(index);
                if (code < 128) {
                  buffer82[i++] = code;
                } else if (code < 2048) {
                  buffer82[i++] = 192 | code >>> 6;
                  buffer82[i++] = 128 | code & 63;
                } else if (code < 55296 || code >= 57344) {
                  buffer82[i++] = 224 | code >>> 12;
                  buffer82[i++] = 128 | code >>> 6 & 63;
                  buffer82[i++] = 128 | code & 63;
                } else {
                  code = 65536 + ((code & 1023) << 10 | message.charCodeAt(++index) & 1023);
                  buffer82[i++] = 240 | code >>> 18;
                  buffer82[i++] = 128 | code >>> 12 & 63;
                  buffer82[i++] = 128 | code >>> 6 & 63;
                  buffer82[i++] = 128 | code & 63;
                }
              }
            } else {
              for (i = this.start; index < length && i < 64; ++index) {
                code = message.charCodeAt(index);
                if (code < 128) {
                  blocks2[i >>> 2] |= code << SHIFT[i++ & 3];
                } else if (code < 2048) {
                  blocks2[i >>> 2] |= (192 | code >>> 6) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code & 63) << SHIFT[i++ & 3];
                } else if (code < 55296 || code >= 57344) {
                  blocks2[i >>> 2] |= (224 | code >>> 12) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code >>> 6 & 63) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code & 63) << SHIFT[i++ & 3];
                } else {
                  code = 65536 + ((code & 1023) << 10 | message.charCodeAt(++index) & 1023);
                  blocks2[i >>> 2] |= (240 | code >>> 18) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code >>> 12 & 63) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code >>> 6 & 63) << SHIFT[i++ & 3];
                  blocks2[i >>> 2] |= (128 | code & 63) << SHIFT[i++ & 3];
                }
              }
            }
          } else {
            if (ARRAY_BUFFER) {
              for (i = this.start; index < length && i < 64; ++index) {
                buffer82[i++] = message[index];
              }
            } else {
              for (i = this.start; index < length && i < 64; ++index) {
                blocks2[i >>> 2] |= message[index] << SHIFT[i++ & 3];
              }
            }
          }
          this.lastByteIndex = i;
          this.bytes += i - this.start;
          if (i >= 64) {
            this.start = i - 64;
            this.hash();
            this.hashed = true;
          } else {
            this.start = i;
          }
        }
        if (this.bytes > 4294967295) {
          this.hBytes += this.bytes / 4294967296 << 0;
          this.bytes = this.bytes % 4294967296;
        }
        return this;
      };
      Md5.prototype.finalize = function() {
        if (this.finalized) {
          return;
        }
        this.finalized = true;
        var blocks2 = this.blocks, i = this.lastByteIndex;
        blocks2[i >>> 2] |= EXTRA[i & 3];
        if (i >= 56) {
          if (!this.hashed) {
            this.hash();
          }
          blocks2[0] = blocks2[16];
          blocks2[16] = blocks2[1] = blocks2[2] = blocks2[3] = blocks2[4] = blocks2[5] = blocks2[6] = blocks2[7] = blocks2[8] = blocks2[9] = blocks2[10] = blocks2[11] = blocks2[12] = blocks2[13] = blocks2[14] = blocks2[15] = 0;
        }
        blocks2[14] = this.bytes << 3;
        blocks2[15] = this.hBytes << 3 | this.bytes >>> 29;
        this.hash();
      };
      Md5.prototype.hash = function() {
        var a, b, c, d, bc, da, blocks2 = this.blocks;
        if (this.first) {
          a = blocks2[0] - 680876937;
          a = (a << 7 | a >>> 25) - 271733879 << 0;
          d = (-1732584194 ^ a & 2004318071) + blocks2[1] - 117830708;
          d = (d << 12 | d >>> 20) + a << 0;
          c = (-271733879 ^ d & (a ^ -271733879)) + blocks2[2] - 1126478375;
          c = (c << 17 | c >>> 15) + d << 0;
          b = (a ^ c & (d ^ a)) + blocks2[3] - 1316259209;
          b = (b << 22 | b >>> 10) + c << 0;
        } else {
          a = this.h0;
          b = this.h1;
          c = this.h2;
          d = this.h3;
          a += (d ^ b & (c ^ d)) + blocks2[0] - 680876936;
          a = (a << 7 | a >>> 25) + b << 0;
          d += (c ^ a & (b ^ c)) + blocks2[1] - 389564586;
          d = (d << 12 | d >>> 20) + a << 0;
          c += (b ^ d & (a ^ b)) + blocks2[2] + 606105819;
          c = (c << 17 | c >>> 15) + d << 0;
          b += (a ^ c & (d ^ a)) + blocks2[3] - 1044525330;
          b = (b << 22 | b >>> 10) + c << 0;
        }
        a += (d ^ b & (c ^ d)) + blocks2[4] - 176418897;
        a = (a << 7 | a >>> 25) + b << 0;
        d += (c ^ a & (b ^ c)) + blocks2[5] + 1200080426;
        d = (d << 12 | d >>> 20) + a << 0;
        c += (b ^ d & (a ^ b)) + blocks2[6] - 1473231341;
        c = (c << 17 | c >>> 15) + d << 0;
        b += (a ^ c & (d ^ a)) + blocks2[7] - 45705983;
        b = (b << 22 | b >>> 10) + c << 0;
        a += (d ^ b & (c ^ d)) + blocks2[8] + 1770035416;
        a = (a << 7 | a >>> 25) + b << 0;
        d += (c ^ a & (b ^ c)) + blocks2[9] - 1958414417;
        d = (d << 12 | d >>> 20) + a << 0;
        c += (b ^ d & (a ^ b)) + blocks2[10] - 42063;
        c = (c << 17 | c >>> 15) + d << 0;
        b += (a ^ c & (d ^ a)) + blocks2[11] - 1990404162;
        b = (b << 22 | b >>> 10) + c << 0;
        a += (d ^ b & (c ^ d)) + blocks2[12] + 1804603682;
        a = (a << 7 | a >>> 25) + b << 0;
        d += (c ^ a & (b ^ c)) + blocks2[13] - 40341101;
        d = (d << 12 | d >>> 20) + a << 0;
        c += (b ^ d & (a ^ b)) + blocks2[14] - 1502002290;
        c = (c << 17 | c >>> 15) + d << 0;
        b += (a ^ c & (d ^ a)) + blocks2[15] + 1236535329;
        b = (b << 22 | b >>> 10) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[1] - 165796510;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[6] - 1069501632;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[11] + 643717713;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[0] - 373897302;
        b = (b << 20 | b >>> 12) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[5] - 701558691;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[10] + 38016083;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[15] - 660478335;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[4] - 405537848;
        b = (b << 20 | b >>> 12) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[9] + 568446438;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[14] - 1019803690;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[3] - 187363961;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[8] + 1163531501;
        b = (b << 20 | b >>> 12) + c << 0;
        a += (c ^ d & (b ^ c)) + blocks2[13] - 1444681467;
        a = (a << 5 | a >>> 27) + b << 0;
        d += (b ^ c & (a ^ b)) + blocks2[2] - 51403784;
        d = (d << 9 | d >>> 23) + a << 0;
        c += (a ^ b & (d ^ a)) + blocks2[7] + 1735328473;
        c = (c << 14 | c >>> 18) + d << 0;
        b += (d ^ a & (c ^ d)) + blocks2[12] - 1926607734;
        b = (b << 20 | b >>> 12) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[5] - 378558;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[8] - 2022574463;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[11] + 1839030562;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[14] - 35309556;
        b = (b << 23 | b >>> 9) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[1] - 1530992060;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[4] + 1272893353;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[7] - 155497632;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[10] - 1094730640;
        b = (b << 23 | b >>> 9) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[13] + 681279174;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[0] - 358537222;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[3] - 722521979;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[6] + 76029189;
        b = (b << 23 | b >>> 9) + c << 0;
        bc = b ^ c;
        a += (bc ^ d) + blocks2[9] - 640364487;
        a = (a << 4 | a >>> 28) + b << 0;
        d += (bc ^ a) + blocks2[12] - 421815835;
        d = (d << 11 | d >>> 21) + a << 0;
        da = d ^ a;
        c += (da ^ b) + blocks2[15] + 530742520;
        c = (c << 16 | c >>> 16) + d << 0;
        b += (da ^ c) + blocks2[2] - 995338651;
        b = (b << 23 | b >>> 9) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[0] - 198630844;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[7] + 1126891415;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[14] - 1416354905;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[5] - 57434055;
        b = (b << 21 | b >>> 11) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[12] + 1700485571;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[3] - 1894986606;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[10] - 1051523;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[1] - 2054922799;
        b = (b << 21 | b >>> 11) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[8] + 1873313359;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[15] - 30611744;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[6] - 1560198380;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[13] + 1309151649;
        b = (b << 21 | b >>> 11) + c << 0;
        a += (c ^ (b | ~d)) + blocks2[4] - 145523070;
        a = (a << 6 | a >>> 26) + b << 0;
        d += (b ^ (a | ~c)) + blocks2[11] - 1120210379;
        d = (d << 10 | d >>> 22) + a << 0;
        c += (a ^ (d | ~b)) + blocks2[2] + 718787259;
        c = (c << 15 | c >>> 17) + d << 0;
        b += (d ^ (c | ~a)) + blocks2[9] - 343485551;
        b = (b << 21 | b >>> 11) + c << 0;
        if (this.first) {
          this.h0 = a + 1732584193 << 0;
          this.h1 = b - 271733879 << 0;
          this.h2 = c - 1732584194 << 0;
          this.h3 = d + 271733878 << 0;
          this.first = false;
        } else {
          this.h0 = this.h0 + a << 0;
          this.h1 = this.h1 + b << 0;
          this.h2 = this.h2 + c << 0;
          this.h3 = this.h3 + d << 0;
        }
      };
      Md5.prototype.hex = function() {
        this.finalize();
        var h0 = this.h0, h1 = this.h1, h2 = this.h2, h3 = this.h3;
        return HEX_CHARS[h0 >>> 4 & 15] + HEX_CHARS[h0 & 15] + HEX_CHARS[h0 >>> 12 & 15] + HEX_CHARS[h0 >>> 8 & 15] + HEX_CHARS[h0 >>> 20 & 15] + HEX_CHARS[h0 >>> 16 & 15] + HEX_CHARS[h0 >>> 28 & 15] + HEX_CHARS[h0 >>> 24 & 15] + HEX_CHARS[h1 >>> 4 & 15] + HEX_CHARS[h1 & 15] + HEX_CHARS[h1 >>> 12 & 15] + HEX_CHARS[h1 >>> 8 & 15] + HEX_CHARS[h1 >>> 20 & 15] + HEX_CHARS[h1 >>> 16 & 15] + HEX_CHARS[h1 >>> 28 & 15] + HEX_CHARS[h1 >>> 24 & 15] + HEX_CHARS[h2 >>> 4 & 15] + HEX_CHARS[h2 & 15] + HEX_CHARS[h2 >>> 12 & 15] + HEX_CHARS[h2 >>> 8 & 15] + HEX_CHARS[h2 >>> 20 & 15] + HEX_CHARS[h2 >>> 16 & 15] + HEX_CHARS[h2 >>> 28 & 15] + HEX_CHARS[h2 >>> 24 & 15] + HEX_CHARS[h3 >>> 4 & 15] + HEX_CHARS[h3 & 15] + HEX_CHARS[h3 >>> 12 & 15] + HEX_CHARS[h3 >>> 8 & 15] + HEX_CHARS[h3 >>> 20 & 15] + HEX_CHARS[h3 >>> 16 & 15] + HEX_CHARS[h3 >>> 28 & 15] + HEX_CHARS[h3 >>> 24 & 15];
      };
      Md5.prototype.toString = Md5.prototype.hex;
      Md5.prototype.digest = function() {
        this.finalize();
        var h0 = this.h0, h1 = this.h1, h2 = this.h2, h3 = this.h3;
        return [
          h0 & 255,
          h0 >>> 8 & 255,
          h0 >>> 16 & 255,
          h0 >>> 24 & 255,
          h1 & 255,
          h1 >>> 8 & 255,
          h1 >>> 16 & 255,
          h1 >>> 24 & 255,
          h2 & 255,
          h2 >>> 8 & 255,
          h2 >>> 16 & 255,
          h2 >>> 24 & 255,
          h3 & 255,
          h3 >>> 8 & 255,
          h3 >>> 16 & 255,
          h3 >>> 24 & 255
        ];
      };
      Md5.prototype.array = Md5.prototype.digest;
      Md5.prototype.arrayBuffer = function() {
        this.finalize();
        var buffer2 = new ArrayBuffer(16);
        var blocks2 = new Uint32Array(buffer2);
        blocks2[0] = this.h0;
        blocks2[1] = this.h1;
        blocks2[2] = this.h2;
        blocks2[3] = this.h3;
        return buffer2;
      };
      Md5.prototype.buffer = Md5.prototype.arrayBuffer;
      Md5.prototype.base64 = function() {
        var v1, v2, v3, base64Str = "", bytes = this.array();
        for (var i = 0; i < 15; ) {
          v1 = bytes[i++];
          v2 = bytes[i++];
          v3 = bytes[i++];
          base64Str += BASE64_ENCODE_CHAR[v1 >>> 2] + BASE64_ENCODE_CHAR[(v1 << 4 | v2 >>> 4) & 63] + BASE64_ENCODE_CHAR[(v2 << 2 | v3 >>> 6) & 63] + BASE64_ENCODE_CHAR[v3 & 63];
        }
        v1 = bytes[i];
        base64Str += BASE64_ENCODE_CHAR[v1 >>> 2] + BASE64_ENCODE_CHAR[v1 << 4 & 63] + "==";
        return base64Str;
      };
      function HmacMd5(key, sharedMemory) {
        var i, result = formatMessage(key);
        key = result[0];
        if (result[1]) {
          var bytes = [], length = key.length, index = 0, code;
          for (i = 0; i < length; ++i) {
            code = key.charCodeAt(i);
            if (code < 128) {
              bytes[index++] = code;
            } else if (code < 2048) {
              bytes[index++] = 192 | code >>> 6;
              bytes[index++] = 128 | code & 63;
            } else if (code < 55296 || code >= 57344) {
              bytes[index++] = 224 | code >>> 12;
              bytes[index++] = 128 | code >>> 6 & 63;
              bytes[index++] = 128 | code & 63;
            } else {
              code = 65536 + ((code & 1023) << 10 | key.charCodeAt(++i) & 1023);
              bytes[index++] = 240 | code >>> 18;
              bytes[index++] = 128 | code >>> 12 & 63;
              bytes[index++] = 128 | code >>> 6 & 63;
              bytes[index++] = 128 | code & 63;
            }
          }
          key = bytes;
        }
        if (key.length > 64) {
          key = new Md5(true).update(key).array();
        }
        var oKeyPad = [], iKeyPad = [];
        for (i = 0; i < 64; ++i) {
          var b = key[i] || 0;
          oKeyPad[i] = 92 ^ b;
          iKeyPad[i] = 54 ^ b;
        }
        Md5.call(this, sharedMemory);
        this.update(iKeyPad);
        this.oKeyPad = oKeyPad;
        this.inner = true;
        this.sharedMemory = sharedMemory;
      }
      HmacMd5.prototype = new Md5();
      HmacMd5.prototype.finalize = function() {
        Md5.prototype.finalize.call(this);
        if (this.inner) {
          this.inner = false;
          var innerHash = this.array();
          Md5.call(this, this.sharedMemory);
          this.update(this.oKeyPad);
          this.update(innerHash);
          Md5.prototype.finalize.call(this);
        }
      };
      var exports2 = createMethod();
      exports2.md5 = exports2;
      exports2.md5.hmac = createHmacMethod();
      if (COMMON_JS) {
        module.exports = exports2;
      } else {
        root.md5 = exports2;
        if (AMD) {
          define(function() {
            return exports2;
          });
        }
      }
    })();
  }
});

// src/core/video.js
var BVID_RE = /(BV[0-9A-Za-z]{10,})/;
function extractBvid(input) {
  if (!input) return "";
  const match = String(input).match(BVID_RE);
  return match ? match[1] : "";
}
function getUrlPage(input) {
  if (!input) return 1;
  try {
    const url = new URL(String(input));
    const page = Number(url.searchParams.get("p") || url.searchParams.get("page") || 1);
    return Number.isFinite(page) && page > 0 ? Math.floor(page) : 1;
  } catch (_error) {
    return 1;
  }
}
function normalizeVideoUrl(input) {
  const bvid = extractBvid(input);
  return bvid ? `https://www.bilibili.com/video/${bvid}/` : "";
}

// src/core/wbi.js
var import_js_md5 = __toESM(require_md5(), 1);
var MIXIN_KEY_ENC_TAB = [
  46,
  47,
  18,
  2,
  53,
  8,
  23,
  32,
  15,
  50,
  10,
  31,
  58,
  3,
  45,
  35,
  27,
  43,
  5,
  49,
  33,
  9,
  42,
  19,
  29,
  28,
  14,
  39,
  12,
  38,
  41,
  13,
  37,
  48,
  7,
  16,
  24,
  55,
  40,
  61,
  26,
  17,
  0,
  1,
  60,
  51,
  30,
  4,
  22,
  25,
  54,
  21,
  56,
  59,
  6,
  63,
  57,
  62,
  11,
  36,
  20,
  34,
  44,
  52
];
function extractWbiKeyFromUrl(input) {
  if (!input) return "";
  try {
    const url = new URL(String(input));
    return (url.pathname.split("/").pop() || "").replace(/\.(png|jpg|webp)$/i, "");
  } catch (_error) {
    return String(input).split("/").pop().replace(/\.(png|jpg|webp)$/i, "");
  }
}
function getMixinKey(imgKey, subKey) {
  const raw = `${imgKey || ""}${subKey || ""}`;
  if (raw.length < 64) {
    throw new Error("Invalid WBI key material");
  }
  return MIXIN_KEY_ENC_TAB.map((index) => raw[index]).join("").slice(0, 32);
}
function signWbiParams(params, mixinKey, options = {}) {
  if (!mixinKey) {
    throw new Error("Missing WBI mixin key");
  }
  const wts = Number.isFinite(Number(options.wts)) ? Number(options.wts) : Math.floor(Date.now() / 1e3);
  const normalized = {};
  for (const [key, value] of Object.entries({ ...params || {}, wts })) {
    if (value === void 0 || value === null || value === "") continue;
    normalized[key] = String(value).replace(/[!'()*]/g, "");
  }
  const baseQuery = Object.keys(normalized).sort().map((key) => `${encodeURIComponent(key)}=${encodeURIComponent(normalized[key])}`).join("&");
  const wRid = (0, import_js_md5.default)(`${baseQuery}${mixinKey}`);
  const signedParams = { ...normalized, w_rid: wRid };
  return {
    params: signedParams,
    query: `${baseQuery}&w_rid=${wRid}`
  };
}

// src/core/bilibili-client.js
var API_BASE = "https://api.bilibili.com";
var BilibiliApiError = class extends Error {
  constructor(message, options = {}) {
    super(message);
    this.name = "BilibiliApiError";
    this.code = options.code || "BILIBILI_API_ERROR";
    this.status = options.status || 0;
    this.details = options.details || null;
  }
};
var BilibiliClient = class {
  constructor(options = {}) {
    this.fetchImpl = options.fetchImpl || globalThis.fetch?.bind(globalThis);
    this.credentials = options.credentials || "include";
    this.wbiCache = null;
  }
  async fetchVideoView(options = {}) {
    const bvid = options.bvid || extractBvid(options.url);
    if (!bvid) {
      throw new BilibiliApiError("No BV id found in the current Bilibili URL", { code: "MISSING_BVID" });
    }
    const payload = await this.fetchJson("/x/web-interface/view", {
      params: { bvid },
      signal: options.signal
    });
    const data = requireOkPayload(payload, "video view");
    const pageNumber = Number(options.page) || getUrlPage(options.url);
    const pages = Array.isArray(data.pages) ? data.pages : [];
    const selectedPage = pages.find((page) => Number(page.page) === pageNumber) || pages[0] || null;
    return {
      bvid,
      aid: Number(data.aid) || 0,
      title: data.title || "",
      description: data.desc || "",
      url: normalizeVideoUrl(options.url || bvid),
      owner: data.owner ? {
        mid: String(data.owner.mid || ""),
        name: data.owner.name || "",
        avatar: data.owner.face || ""
      } : null,
      page: selectedPage ? {
        cid: Number(selectedPage.cid) || 0,
        page: Number(selectedPage.page) || 1,
        part: selectedPage.part || "",
        duration: Number(selectedPage.duration) || 0
      } : null,
      pages: pages.map((page) => ({
        cid: Number(page.cid) || 0,
        page: Number(page.page) || 0,
        part: page.part || "",
        duration: Number(page.duration) || 0
      }))
    };
  }
  async fetchMainComments(options = {}) {
    const params = {
      type: 1,
      oid: options.oid,
      mode: options.mode || 2,
      plat: 1,
      web_location: 1315875
    };
    if (options.offset) {
      params.pagination_str = JSON.stringify({ offset: options.offset });
    }
    const payload = await this.fetchJson("/x/v2/reply/wbi/main", {
      params,
      signed: true,
      signal: options.signal
    });
    const data = requireOkPayload(payload, "main comments");
    if (data.v_voucher) {
      throw new BilibiliApiError("Bilibili requested an extra verification voucher for comments", {
        code: "BILIBILI_VOUCHER_REQUIRED"
      });
    }
    return {
      cursor: data.cursor || {},
      replies: Array.isArray(data.replies) ? data.replies : [],
      topReplies: Array.isArray(data.top_replies) ? data.top_replies : [],
      hots: Array.isArray(data.hots) ? data.hots : [],
      config: data.config || null,
      control: data.control || null
    };
  }
  async fetchNestedReplies(options = {}) {
    const payload = await this.fetchJson("/x/v2/reply/reply", {
      params: {
        type: 1,
        oid: options.oid,
        root: options.root,
        ps: Math.max(1, Math.min(20, Number(options.ps) || 20)),
        pn: Math.max(1, Number(options.pn) || 1)
      },
      signal: options.signal
    });
    const data = requireOkPayload(payload, "nested replies");
    return {
      page: data.page || {},
      root: data.root || null,
      replies: Array.isArray(data.replies) ? data.replies : []
    };
  }
  async fetchWbiKeys(options = {}) {
    const now = Date.now();
    if (this.wbiCache && this.wbiCache.expiresAt > now) return this.wbiCache;
    const payload = await this.fetchJson("/x/web-interface/nav", {
      signal: options.signal,
      allowNonZeroCode: true
    });
    const wbiImg = payload?.data?.wbi_img;
    const imgKey = extractWbiKeyFromUrl(wbiImg?.img_url);
    const subKey = extractWbiKeyFromUrl(wbiImg?.sub_url);
    if (!imgKey || !subKey) {
      throw new BilibiliApiError("Could not resolve Bilibili WBI keys", {
        code: "MISSING_WBI_KEYS",
        details: { responseCode: payload?.code }
      });
    }
    this.wbiCache = {
      imgKey,
      subKey,
      mixinKey: getMixinKey(imgKey, subKey),
      expiresAt: now + 6 * 60 * 60 * 1e3
    };
    return this.wbiCache;
  }
  async fetchJson(pathOrUrl, options = {}) {
    if (!this.fetchImpl) {
      throw new BilibiliApiError("No fetch implementation is available", { code: "FETCH_UNAVAILABLE" });
    }
    const url = new URL(pathOrUrl.startsWith("http") ? pathOrUrl : `${API_BASE}${pathOrUrl}`);
    let query = "";
    if (options.signed) {
      const keys = await this.fetchWbiKeys({ signal: options.signal });
      query = signWbiParams(options.params || {}, keys.mixinKey).query;
    } else {
      query = makeQuery(options.params || {});
    }
    if (query) url.search = query;
    const response = await this.fetchImpl(url.toString(), {
      method: "GET",
      credentials: this.credentials,
      cache: "no-store",
      redirect: "follow",
      signal: options.signal,
      headers: {
        accept: "application/json, text/plain, */*"
      }
    });
    if (!response.ok) {
      throw new BilibiliApiError(`Request failed with HTTP ${response.status}`, {
        code: "HTTP_ERROR",
        status: response.status,
        details: { url: stripQuery(url.toString()) }
      });
    }
    let payload;
    try {
      payload = await response.json();
    } catch (error) {
      throw new BilibiliApiError("Bilibili response was not valid JSON", {
        code: "INVALID_JSON",
        status: response.status,
        details: { cause: error.message }
      });
    }
    if (!options.allowNonZeroCode && Number(payload?.code) !== 0) {
      throw new BilibiliApiError(payload?.message || `Bilibili returned code ${payload?.code}`, {
        code: "BILIBILI_RESPONSE_ERROR",
        details: { responseCode: payload?.code, url: stripQuery(url.toString()) }
      });
    }
    return payload;
  }
};
function requireOkPayload(payload, source) {
  if (!payload || typeof payload !== "object") {
    throw new BilibiliApiError(`${source} returned an empty response`, { code: "EMPTY_RESPONSE" });
  }
  if (Number(payload.code) !== 0) {
    throw new BilibiliApiError(payload.message || `${source} returned code ${payload.code}`, {
      code: "BILIBILI_RESPONSE_ERROR",
      details: { responseCode: payload.code, source }
    });
  }
  return payload.data || {};
}
function makeQuery(params) {
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== void 0 && value !== null && value !== "") {
      query.set(key, String(value));
    }
  }
  return query.toString();
}
function stripQuery(input) {
  try {
    const url = new URL(input);
    url.search = "";
    return url.toString();
  } catch (_error) {
    return String(input).split("?")[0];
  }
}

// src/core/model.js
var COMMENT_ORDERS = /* @__PURE__ */ new Set(["default", "latest"]);
function normalizeApiComment(comment, options = {}) {
  const id = toId(comment?.rpid_str || comment?.rpid);
  const rootId = toId(comment?.root_str || comment?.root);
  const parentId = toId(comment?.parent_str || comment?.parent);
  const ctime = toNumber(comment?.ctime, 0);
  const suppliedReplies = Array.isArray(options.replies) ? options.replies : Array.isArray(comment?.replies) ? comment.replies : [];
  return {
    id,
    rpid: id,
    oid: toId(comment?.oid),
    type: toNumber(comment?.type, 1),
    level: options.level || (rootId && rootId !== "0" ? "reply" : "root"),
    rootId: rootId && rootId !== "0" ? rootId : null,
    parentId: parentId && parentId !== "0" ? parentId : null,
    dialogId: toId(comment?.dialog_str || comment?.dialog) || null,
    floor: toNumber(comment?.floor, 0),
    createdAt: ctime > 0 ? new Date(ctime * 1e3).toISOString() : null,
    ctime,
    author: normalizeAuthor(comment?.member, comment?.mid),
    content: normalizeContent(comment?.content),
    metrics: {
      like: toNumber(comment?.like, 0),
      replyCount: toNumber(comment?.rcount ?? comment?.count, 0),
      childCount: toNumber(comment?.count, 0)
    },
    flags: {
      upLiked: Boolean(comment?.up_action?.like),
      upReplied: Boolean(comment?.up_action?.reply),
      invisible: Boolean(comment?.invisible),
      folded: Boolean(comment?.folder?.is_folded)
    },
    source: {
      section: options.sourceSection || options.section || (options.level === "reply" ? "reply" : "normal"),
      page: toNumber(options.sourcePage, 0),
      indexInPage: toNumber(options.sourceIndex, 0),
      order: options.sourceOrder || "",
      apiMode: options.apiMode || null,
      fetchedAt: options.fetchedAt || null
    },
    replyControl: comment?.reply_control ? {
      timeDesc: comment.reply_control.time_desc || "",
      location: comment.reply_control.location || ""
    } : null,
    raw: {
      state: comment?.state ?? null,
      attr: comment?.attr ?? null,
      assist: comment?.assist ?? null,
      rpid_str: comment?.rpid_str || null,
      root_str: comment?.root_str || null,
      parent_str: comment?.parent_str || null
    },
    replies: suppliedReplies.map(
      (reply) => normalizeApiComment(reply, {
        level: "reply",
        sourceSection: "reply",
        sourcePage: options.replySourcePage || options.sourcePage || 0,
        sourceIndex: options.replySourceIndex || 0,
        sourceOrder: options.replySourceOrder || options.sourceOrder || "",
        apiMode: options.replyApiMode || null,
        fetchedAt: options.fetchedAt || null
      })
    )
  };
}
function sortComments(comments, order = "default") {
  const normalizedOrder = COMMENT_ORDERS.has(order) ? order : "default";
  if (normalizedOrder === "default") return [...comments || []];
  return [...comments || []].sort((a, b) => {
    const left = toNumber(a?.ctime, 0);
    const right = toNumber(b?.ctime, 0);
    if (left !== right) return right - left;
    return 0;
  });
}
function normalizeAuthor(member, fallbackMid) {
  return {
    mid: toId(member?.mid || fallbackMid),
    name: member?.uname || member?.name || "",
    avatar: member?.avatar || "",
    level: toNumber(member?.level_info?.current_level, 0),
    officialType: toNumber(member?.official_verify?.type, -1),
    officialDesc: member?.official_verify?.desc || "",
    vipLabel: member?.vip?.label?.text || ""
  };
}
function normalizeContent(content) {
  const emote = content?.emote && typeof content.emote === "object" ? content.emote : {};
  const pictures = Array.isArray(content?.pictures) ? content.pictures : [];
  return {
    message: content?.message || "",
    platform: toNumber(content?.plat, 0),
    device: content?.device || "",
    emotes: Object.values(emote).map((item) => ({
      text: item?.text || "",
      url: item?.url || "",
      size: toNumber(item?.meta?.size, 0)
    })),
    pictures: pictures.map((item) => ({
      url: item?.img_src || item?.url || "",
      width: toNumber(item?.img_width || item?.width, 0),
      height: toNumber(item?.img_height || item?.height, 0)
    }))
  };
}
function toId(value) {
  if (value === void 0 || value === null || value === "") return "";
  return String(value);
}
function toNumber(value, fallback) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

// src/core/capture.js
var DEFAULT_CAPTURE_OPTIONS = {
  rootOrder: "default",
  rootMaxPages: 20,
  rootMaxItems: 100,
  includeReplies: true,
  replyOrder: "default",
  replyMaxPagesPerRoot: 1,
  replyMaxItemsPerRoot: 5,
  requestDelayMs: 150
};
var ORDER_VALUES = /* @__PURE__ */ new Set(["default", "latest"]);
function normalizeCaptureOptions(input = {}) {
  return {
    rootOrder: normalizeOrder(input.rootOrder, DEFAULT_CAPTURE_OPTIONS.rootOrder),
    rootMaxPages: normalizeLimit(input.rootMaxPages, DEFAULT_CAPTURE_OPTIONS.rootMaxPages, { min: 1, max: 5e3 }),
    rootMaxItems: normalizeLimit(input.rootMaxItems, DEFAULT_CAPTURE_OPTIONS.rootMaxItems, { min: 1, max: 1e6 }),
    includeReplies: input.includeReplies !== false,
    replyOrder: normalizeOrder(input.replyOrder, DEFAULT_CAPTURE_OPTIONS.replyOrder),
    replyMaxPagesPerRoot: normalizeLimit(input.replyMaxPagesPerRoot, DEFAULT_CAPTURE_OPTIONS.replyMaxPagesPerRoot, {
      min: 1,
      max: 500
    }),
    replyMaxItemsPerRoot: normalizeLimit(input.replyMaxItemsPerRoot, DEFAULT_CAPTURE_OPTIONS.replyMaxItemsPerRoot, {
      min: 0,
      max: 1e5
    }),
    requestDelayMs: normalizeFiniteNumber(input.requestDelayMs, DEFAULT_CAPTURE_OPTIONS.requestDelayMs, {
      min: 0,
      max: 5e3
    })
  };
}
async function captureVideoComments(request = {}, runtime = {}) {
  const options = normalizeCaptureOptions(request.options || {});
  const client = runtime.client || new BilibiliClient();
  const signal = runtime.signal || null;
  const onProgress = typeof runtime.onProgress === "function" ? runtime.onProgress : () => {
  };
  const bvid = request.bvid || extractBvid(request.url);
  checkAbort(signal);
  onProgress({ phase: "video", message: "Resolving video metadata" });
  const video = await client.fetchVideoView({ bvid, url: request.url, signal });
  if (!video.aid) {
    throw new Error("\u65E0\u6CD5\u8BC6\u522B\u8FD9\u4E2A B \u7AD9\u89C6\u9891\u7684 AV \u53F7");
  }
  const fetchedRootComments = [];
  const fetchedPinnedComments = [];
  const rootMode = options.rootOrder === "latest" ? 2 : 3;
  let offset = "";
  let rootPage = 0;
  let reachedRootEnd = false;
  const requestedRootOffsets = /* @__PURE__ */ new Set();
  while (rootPage < options.rootMaxPages) {
    checkAbort(signal);
    if (requestedRootOffsets.has(offset)) {
      reachedRootEnd = true;
      break;
    }
    requestedRootOffsets.add(offset);
    rootPage += 1;
    onProgress({ phase: "root", page: rootPage, fetched: fetchedRootComments.length });
    const page = await client.fetchMainComments({
      oid: video.aid,
      mode: rootMode,
      offset,
      signal
    });
    const fetchedAt = (/* @__PURE__ */ new Date()).toISOString();
    for (const [index, reply] of page.topReplies.entries()) {
      fetchedPinnedComments.push(
        normalizeApiComment(reply, {
          level: "root",
          sourceSection: "pinned",
          sourcePage: rootPage,
          sourceIndex: index,
          sourceOrder: options.rootOrder,
          apiMode: rootMode,
          fetchedAt
        })
      );
    }
    for (const [index, reply] of page.replies.entries()) {
      fetchedRootComments.push(
        normalizeApiComment(reply, {
          level: "root",
          sourceSection: "normal",
          sourcePage: rootPage,
          sourceIndex: index,
          sourceOrder: options.rootOrder,
          apiMode: rootMode,
          fetchedAt
        })
      );
    }
    offset = page.cursor?.pagination_reply?.next_offset || "";
    reachedRootEnd = Boolean(page.cursor?.is_end) || !offset || page.replies.length === 0;
    const selectableCount = countSelectableRootComments(fetchedRootComments, fetchedPinnedComments);
    if (reachedRootEnd || hasReachedFiniteCount(selectableCount, options.rootMaxItems)) break;
    await delay(options.requestDelayMs, signal);
  }
  const pinnedComments = dedupeById(fetchedPinnedComments);
  const pinnedIds = new Set(pinnedComments.map((comment) => comment.id).filter(Boolean));
  const selectableRootComments = dedupeById(fetchedRootComments.filter((comment) => !pinnedIds.has(comment.id)));
  const selectedRoots = sortComments(selectableRootComments, options.rootOrder).slice(0, finiteSliceEnd(options.rootMaxItems));
  let fetchedReplyPages = 0;
  let nestedReplies = 0;
  const replyRoots = [...pinnedComments, ...selectedRoots];
  if (options.includeReplies && options.replyMaxItemsPerRoot > 0) {
    for (const [index, root] of replyRoots.entries()) {
      checkAbort(signal);
      if (root.metrics.replyCount <= 0 && !(root.replies || []).length) {
        root.replies = [];
        continue;
      }
      onProgress({
        phase: "reply",
        rootIndex: index + 1,
        rootTotal: replyRoots.length,
        rootId: root.id,
        fetched: nestedReplies
      });
      const replies = await fetchRepliesForRoot(client, video.aid, root, options, signal, (count) => {
        fetchedReplyPages += count;
      });
      root.replies = replies;
      nestedReplies += replies.length;
      await delay(options.requestDelayMs, signal);
    }
  } else {
    for (const root of replyRoots) root.replies = [];
  }
  const generatedAt = (/* @__PURE__ */ new Date()).toISOString();
  return {
    schemaVersion: "bili-comment-capture/v1",
    generatedAt,
    source: {
      kind: "chrome-extension",
      api: "bilibili-web-comment-api",
      pageUrl: request.url || video.url || "",
      commentSystem: {
        rootPagination: "cursor",
        rootCursorField: "cursor.pagination_reply.next_offset",
        rootPageSize: 20,
        replyPagination: "page-number",
        replyPageSize: 20
      }
    },
    video,
    options: serializeCaptureOptions(options),
    stats: {
      pinnedComments: pinnedComments.length,
      rootComments: selectedRoots.length,
      nestedReplies,
      fetchedRootPages: rootPage,
      fetchedReplyPages,
      fetchedRootCandidates: fetchedRootComments.length,
      fetchedPinnedCandidates: fetchedPinnedComments.length,
      reachedRootEnd
    },
    pinnedComments,
    comments: selectedRoots
  };
}
async function fetchRepliesForRoot(client, oid, root, options, signal, onPageCount) {
  const replies = getVisibleInlineReplies(root, options.replyOrder);
  let pageNumber = 1;
  const pageSize = 20;
  const canStopOnItemLimit = options.replyOrder !== "latest";
  if (hasReachedFiniteLimit(replies, options.replyMaxItemsPerRoot)) {
    return dedupeById(replies).slice(0, finiteSliceEnd(options.replyMaxItemsPerRoot));
  }
  while (pageNumber <= options.replyMaxPagesPerRoot) {
    checkAbort(signal);
    const page = await client.fetchNestedReplies({
      oid,
      root: root.id,
      pn: pageNumber,
      ps: pageSize,
      signal
    });
    onPageCount(1);
    const beforeUniqueCount = dedupeById(replies).length;
    const fetchedAt = (/* @__PURE__ */ new Date()).toISOString();
    for (const [index, reply] of page.replies.entries()) {
      replies.push(
        normalizeApiComment(reply, {
          level: "reply",
          sourceSection: "reply",
          sourcePage: pageNumber,
          sourceIndex: index,
          sourceOrder: options.replyOrder,
          apiMode: "reply",
          fetchedAt
        })
      );
    }
    const total = Number(page.page?.count) || replies.length;
    const uniqueCount = dedupeById(replies).length;
    const noNewReplies = uniqueCount === beforeUniqueCount && page.replies.length > 0;
    if (page.replies.length === 0 || noNewReplies || canStopOnItemLimit && hasReachedFiniteCount(uniqueCount, options.replyMaxItemsPerRoot) || uniqueCount >= total)
      break;
    pageNumber += 1;
    await delay(options.requestDelayMs, signal);
  }
  return sortComments(dedupeById(replies), options.replyOrder).slice(0, finiteSliceEnd(options.replyMaxItemsPerRoot));
}
function getVisibleInlineReplies(root, order) {
  if (order !== "default") return [];
  return Array.isArray(root?.replies) ? [...root.replies] : [];
}
function normalizeLimit(value, fallback, bounds) {
  if (value === "all" || value === Infinity) return Infinity;
  return normalizeFiniteNumber(value, fallback, bounds);
}
function normalizeOrder(value, fallback) {
  if (ORDER_VALUES.has(value)) return value;
  return fallback;
}
function normalizeFiniteNumber(value, fallback, bounds) {
  const number = Number(value ?? fallback);
  const finite = Number.isFinite(number) ? Math.floor(number) : fallback;
  return Math.min(bounds.max, Math.max(bounds.min, finite));
}
function finiteSliceEnd(value) {
  return value === Infinity ? void 0 : value;
}
function hasReachedFiniteLimit(comments, limit) {
  return hasReachedFiniteCount(dedupeById(comments).length, limit);
}
function hasReachedFiniteCount(count, limit) {
  return limit !== Infinity && count >= limit;
}
function countSelectableRootComments(rootComments, pinnedComments) {
  const pinnedIds = new Set(dedupeById(pinnedComments).map((comment) => comment.id).filter(Boolean));
  return dedupeById(rootComments.filter((comment) => !pinnedIds.has(comment.id))).length;
}
function serializeCaptureOptions(options) {
  const serialized = {};
  for (const [key, value] of Object.entries(options)) {
    serialized[key] = value === Infinity ? "all" : value;
  }
  return serialized;
}
function dedupeById(comments) {
  const seen = /* @__PURE__ */ new Set();
  const output = [];
  for (const comment of comments) {
    if (!comment.id || seen.has(comment.id)) continue;
    seen.add(comment.id);
    output.push(comment);
  }
  return output;
}
function delay(ms, signal) {
  checkAbort(signal);
  if (!ms) return Promise.resolve();
  return new Promise((resolve, reject) => {
    const timer = setTimeout(resolve, ms);
    if (signal) {
      signal.addEventListener(
        "abort",
        () => {
          clearTimeout(timer);
          reject(new DOMException("Capture was cancelled", "AbortError"));
        },
        { once: true }
      );
    }
  });
}
function checkAbort(signal) {
  if (signal?.aborted) {
    throw new DOMException("Capture was cancelled", "AbortError");
  }
}

// src/extension/page-comment-client.js
function createPageCommentClient({ chromeApi, tabId, fallbackClient = new BilibiliClient() } = {}) {
  return {
    fetchVideoView(options) {
      return fallbackClient.fetchVideoView(options);
    },
    fetchNestedReplies(options) {
      return fallbackClient.fetchNestedReplies(options);
    },
    async fetchMainComments(options = {}) {
      if (!tabId) return fallbackClient.fetchMainComments(options);
      const bridgeResult = await fetchPageCommentBatch(chromeApi, tabId, {
        oid: options.oid,
        type: 1,
        mode: options.mode || 3,
        offset: options.offset || "",
        seekRpid: options.seekRpid || ""
      });
      if (!bridgeResult.ok) {
        throw new BilibiliApiError("\u65E0\u6CD5\u8BFB\u53D6\u5F53\u524D\u9875\u9762\u7684\u8BC4\u8BBA\u987A\u5E8F\uFF0C\u8BF7\u5237\u65B0\u5F53\u524D B \u7AD9\u89C6\u9891\u9875\u540E\u91CD\u8BD5", {
          code: "PAGE_COMMENT_BRIDGE_UNAVAILABLE",
          details: { message: bridgeResult.message || "unknown page bridge error" }
        });
      }
      return toMainCommentPage(bridgeResult);
    }
  };
}
async function fetchPageCommentBatch(chromeApi, tabId, args) {
  if (!chromeApi?.scripting?.executeScript) {
    return { ok: false, message: "chrome.scripting.executeScript is unavailable" };
  }
  try {
    const [injection] = await chromeApi.scripting.executeScript({
      target: { tabId },
      world: "MAIN",
      func: fetchBilibiliCommentBatchInPage,
      args: [args]
    });
    return injection?.result || { ok: false, message: "empty page bridge result" };
  } catch (error) {
    return { ok: false, message: error?.message || String(error) };
  }
}
function toMainCommentPage(result) {
  const topReplies = [];
  const replies = [];
  for (const reply of Array.isArray(result.replies) ? result.replies : []) {
    if (reply?.reply_control?.is_up_top === true) {
      topReplies.push(reply);
    } else {
      replies.push(reply);
    }
  }
  return {
    cursor: result.cursor || {},
    replies,
    topReplies,
    hots: [],
    config: null,
    control: null
  };
}
async function fetchBilibiliCommentBatchInPage(args) {
  const tagName = "bili-comments";
  const timeoutMs = 1e4;
  const startedAt = Date.now();
  function waitForComponent() {
    if (customElements.get(tagName)) return Promise.resolve();
    const remaining = Math.max(1, timeoutMs - (Date.now() - startedAt));
    return waitWithTimeout(customElements.whenDefined(tagName), remaining, "bili-comments component is not ready");
  }
  function waitWithTimeout(promise, ms, message) {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error(message)), ms);
      Promise.resolve(promise).then(
        (value) => {
          clearTimeout(timer);
          resolve(value);
        },
        (error) => {
          clearTimeout(timer);
          reject(error);
        }
      );
    });
  }
  function nextOffsetFrom(paginationStr) {
    try {
      return JSON.parse(paginationStr || "{}")?.offset || "";
    } catch (_error) {
      return "";
    }
  }
  function toPlainComments(comments) {
    return JSON.parse(JSON.stringify(comments || []));
  }
  function readActiveSeekRpid(liveElement) {
    if (args.offset) return "";
    const value = args.seekRpid || liveElement?.seekRpid || liveElement?.getAttribute?.("seek-rpid") || liveElement?.getAttribute?.("seek_rpid") || "";
    return value ? String(value) : "";
  }
  function readElementSubject(element) {
    const params = String(element?.getAttribute?.("data-params") || "");
    const [attrType, attrOid] = params.split(",");
    return {
      oid: String(element?.oid || attrOid || ""),
      type: Number(element?.type || attrType || 1),
      mode: Number(element?.mode || element?.getAttribute?.("mode") || 3)
    };
  }
  function isMatchingLiveElement(element) {
    if (!element) return false;
    const subject = readElementSubject(element);
    return subject.oid === String(args.oid || "") && subject.type === (Number(args.type) || 1) && subject.mode === (Number(args.mode) || 3);
  }
  function makeBatchResult(element, comments) {
    return {
      ok: true,
      cursor: {
        is_end: Boolean(element.showEnd),
        pagination_reply: { next_offset: nextOffsetFrom(element.paginationStr) },
        all_count: Number(element.count) || 0
      },
      replies: toPlainComments(comments)
    };
  }
  async function readFromLiveElement(element) {
    if (!isMatchingLiveElement(element)) return null;
    const currentList = Array.isArray(element.list) ? element.list : [];
    if (!args.offset) {
      if (currentList.length > 0) return makeBatchResult(element, currentList);
      if (typeof element.getList === "function") {
        await waitWithTimeout(element.getList(), timeoutMs, "bili-comments.getList timed out");
        return makeBatchResult(element, Array.isArray(element.list) ? element.list : []);
      }
      return null;
    }
    if (typeof element.getList !== "function") return null;
    const liveOffset = nextOffsetFrom(element.paginationStr);
    if (liveOffset && liveOffset !== String(args.offset)) return null;
    const beforeLength = currentList.length;
    await waitWithTimeout(element.getList(), timeoutMs, "bili-comments.getList timed out");
    const nextList = Array.isArray(element.list) ? element.list : [];
    return makeBatchResult(element, nextList.slice(beforeLength));
  }
  try {
    await waitForComponent();
    const liveElement = document.querySelector?.(tagName);
    const liveResult = await readFromLiveElement(liveElement);
    if (liveResult) return liveResult;
    const activeSeekRpid = readActiveSeekRpid(liveElement);
    const element = document.createElement(tagName);
    element.style.cssText = "position:fixed;left:-10000px;top:-10000px;width:1px;height:1px;overflow:hidden;opacity:0;pointer-events:none;";
    document.documentElement.appendChild(element);
    try {
      element.oid = String(args.oid || "");
      element.type = Number(args.type) || 1;
      element.mode = Number(args.mode) || 3;
      element.paginationStr = JSON.stringify({ offset: args.offset || "" });
      element.seekRpid = activeSeekRpid;
      element.cmFromTrackId = "";
      element.showSpinner = false;
      element.showEnd = false;
      element.showContinuations = false;
      element.maxViewLimit = 0;
      element.disableUpActions = true;
      element.fixedCommentBox = false;
      element.loadedID = {};
      element.invisibleID = {};
      element.list = [];
      if (typeof element.getList !== "function") {
        return { ok: false, message: "bili-comments.getList is unavailable" };
      }
      await waitWithTimeout(element.getList(), timeoutMs, "bili-comments.getList timed out");
      return makeBatchResult(element, Array.isArray(element.list) ? element.list : []);
    } finally {
      element.remove();
    }
  } catch (error) {
    return { ok: false, message: error?.message || String(error) };
  }
}

// src/extension/background-entry.js
var PORT_NAME = "bili-comment-capture";
configureSidePanel();
chrome.runtime.onConnect.addListener((port) => {
  if (port.name !== PORT_NAME) return;
  let activeController = null;
  port.onMessage.addListener((message) => {
    if (message?.type === "START_CAPTURE") {
      if (activeController) activeController.abort();
      activeController = new AbortController();
      runCapture(port, message.payload || {}, activeController).catch((error) => {
        port.postMessage({ type: "ERROR", error: serializeError(error) });
      }).finally(() => {
        activeController = null;
      });
      return;
    }
    if (message?.type === "CANCEL_CAPTURE" && activeController) {
      activeController.abort();
    }
  });
  port.onDisconnect.addListener(() => {
    if (activeController) activeController.abort();
  });
});
function configureSidePanel() {
  if (!chrome.sidePanel?.setPanelBehavior) return;
  chrome.sidePanel.setPanelBehavior({ openPanelOnActionClick: true }).catch(() => {
  });
}
async function runCapture(port, payload, controller) {
  port.postMessage({ type: "PROGRESS", payload: { phase: "start", message: "\u5F00\u59CB\u6293\u53D6\u8BC4\u8BBA" } });
  const result = await captureVideoComments(
    {
      url: payload.url,
      bvid: payload.bvid,
      options: payload.options
    },
    {
      client: createPageCommentClient({ chromeApi: chrome, tabId: payload.tabId }),
      signal: controller.signal,
      onProgress(progress) {
        port.postMessage({ type: "PROGRESS", payload: progress });
      }
    }
  );
  await chrome.storage.local.set({
    lastCaptureSummary: {
      generatedAt: result.generatedAt,
      videoTitle: result.video?.title || "",
      bvid: result.video?.bvid || "",
      stats: result.stats
    }
  });
  port.postMessage({ type: "DONE", payload: { result } });
}
function serializeError(error) {
  return {
    name: error?.name || "Error",
    message: error?.message || "Unknown error",
    code: error?.code || "",
    status: error?.status || 0,
    details: error?.details || null
  };
}
