import { cp, mkdir, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distDir = resolve(rootDir, "dist");

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });

const runtimeBundles = [
  {
    sourceEntry: "src/extension/background-entry.js",
    runtimeOutput: "background/background.js",
    bundleFormat: "esm",
  },
  {
    sourceEntry: "src/extension/content-entry.js",
    runtimeOutput: "content/content.js",
    bundleFormat: "iife",
  },
  {
    sourceEntry: "src/extension/sidepanel-entry.js",
    runtimeOutput: "sidepanel/sidepanel.js",
    bundleFormat: "esm",
  },
];

for (const { sourceEntry, runtimeOutput, bundleFormat } of runtimeBundles) {
  for (const baseDir of [rootDir, distDir]) {
    await build({
      entryPoints: [resolve(rootDir, sourceEntry)],
      outfile: resolve(baseDir, runtimeOutput),
      bundle: true,
      format: bundleFormat,
      target: "chrome120",
      banner: {
        js: `// Generated by scripts/build.mjs from ${sourceEntry}. Do not edit this file directly.`,
      },
      legalComments: "none",
      sourcemap: false,
      logLevel: "silent",
    });
  }
  console.log(`built ${runtimeOutput}`);
}

for (const path of [
  "manifest.json",
  "_locales",
  "sidepanel/sidepanel.html",
  "sidepanel/sidepanel.css",
  "icons/icon.svg",
  "icons/icon16.png",
  "icons/icon32.png",
  "icons/icon48.png",
  "icons/icon128.png",
]) {
  await cp(resolve(rootDir, path), resolve(distDir, path), { recursive: true });
}
